### ISSUE TITLE
Vim inside motion doesn't work for [, (, {, t, others? (OS X)

### ISSUE THREAD

**Issue by prurph** [BoostIO/Boostnote#1003]
Expected behavior: typing `ci(` with the cursor in normal mode and inside `(foo)` should delete `foo` and leave the cursor in insert mode inside the remaining `()`.

Actual behavior in Boostnote on OS X: nothing happens and the cursor remains in normal mode.

The same thing happens for other keys like `{`, `[` and `t` (for tag)

These commands work in the Codemirror demo--except for t--just not in Boostnote. It only appears to support `ci"` and `ci'`.

**Comment by asmsuechan** [comment]
Hi, @prurph. Thanks for opening an issue. What you want in Vim mode is not actually Boostnote's issue because we use CodeMirror as the code editor so you should open an issue on CodeMirror. However, I'll try to manage them because chances are that there're ways which I don't know to implement it. If you have it, please let us know.

**Comment by prurph** [comment]
Thank you for responding--the reason I opened it here is because it works [in the CodeMirror demo](https://codemirror.net/demo/vim.html).

For example, go to demo link, put your cursor on the v in `(void)` and do `ci(`. Now try the same thing in Boostnote with Vim bindings on. It works in CodeMirror alone but not in Boostnote.

**Comment by asmsuechan** [comment]
> the reason I opened it here is because it works in the CodeMirror demo.

Oh, I didn't know so I'll review the settings and try to improve.

**Comment by prurph** [comment]
Great--thank you for taking a look! Boostnote is really cool. :]

**Comment by i-give-up** [comment]
Just came across this issue myself

My environment: 

- Windows 8.1
- Boostnote version 0.10.0

Uploaded two videos to compare between behavior on Boostnote and the correct behavior.

- [On Boostnote](https://streamable.com/p7dd6) - nothing happens when pressing the key sequences `di)` and `ci)`
- [On CodeMirror.net's demo](https://streamable.com/6p5ad) - pressing `di)` deletes content inside the parentheses whereas `ci)` deletes content inside parentheses and changes to Insert mode.

These key sequences (i.e. "Vim text objects") also work on Tampermonkey which uses CodeMirror.

Please let me know if you need more information.

**Comment by hidaiy** [comment]
I think there's two reasons why this doesn't work.

## 1. matchbrackets.js is required
According to [demo site](https://codemirror.net/demo/vim.html), `codemirror/addon/edit/matchbrackets.js` is required when we use CodeMirror with Vim mode.

If this module is imported in main.html, we can use `ci[`, `ci(`, etc...
except when brackets have styles(like color or underscore etc..) of html.
And `cit` or `dit` either, it seems like is not supported in CodeMirror.


## 2. CodeMirror seems like having a problem with the Vim mode.
It seems like Vim mode on CodeMirror can't scan brackets when brackets have styles(like color or underscore etc..) of html.

I opened an issue and pull request on CodeMirror repository to ask this issue.

https://github.com/codemirror/CodeMirror/issues/5334
