### ISSUE TITLE
Would love the ability to multi-select notes and modify all at once

### ISSUE THREAD

**Issue by derekantrican** [BoostIO/Boostnote#1058]
Would love to be able to mutli-select a bunch of notes, then drag to a specific folder ("folder" in Boostnote, of course) or mutli-select then delete, etc

**Comment by Nachtalb** [comment]
Would love to see this too 👌👌

**Comment by kazup01** [comment]
Thank you for your suggestion @derekantrican ! that's cool. 
Can somebody make it? If not, @sosukesuzuki will make it.

**Comment by voidsatisfaction** [comment]
@kazup01 I want to try. But as I saw Boostnote code bases, I think until now, it has only dealing with one note so that `MarkdownNoteDetail` and `SnippetNoteDetail` are currently responsible for `deleteNote`. I think it has not been a matter until now because there is only one note delete function. So it can be understood as a `delete` means`click trash button`.

However from now on if we want to implement multi notes delete feature and multi ~ sth, it is inadequate in terms of current implementation. And I don't think `Notelist` also is not responsible for deleting notes..

So, my suggestion is implementing redux-thunk. If we do, `actioncreator` can take responsibility of multi notes deletion and etc.

What do you think about it? @kazup01
