### ISSUE TITLE
Cannot read text when "Adding Storage" on Ubuntu

### ISSUE THREAD

**Issue by karanrajpal14** [BoostIO/Boostnote#1090]
Hello, 
I'm currently running Ubuntu Budgie and I'm unable to read any of the text. They all appear as boxes. Am I missing a particular font you guys use or something of that sort?
![boostnote](https://user-images.githubusercontent.com/3253145/32590917-e47dac78-c542-11e7-81c7-535d6e362e5c.png)

**Comment by kazup01** [comment]
memo: https://github.com/BoostIO/Boostnote/issues/964

**Comment by kazup01** [comment]
Hi @karanrajpal14 , @yosmoc has solved this problem. Could you try it?#1105

**Comment by karanrajpal14** [comment]
Sure. Just give me a couple of hours and I'll try it once I'm back from work. Will report the status soon.

**Comment by kazup01** [comment]
Thank you @karanrajpal14 :)

**Comment by karanrajpal14** [comment]
@kazup01 @yosmoc how exactly do I upgrade electron for boostnote? If I'm not wrong, it needs to be updated within boostnote, correct? Or is there something I can do on my end?

**Comment by yosmoc** [comment]
Hi @karanrajpal14,

If you can build my PR branch by yourself, you will get the boostnote with electron 1.6.15. You can find instruction in [here](https://github.com/BoostIO/Boostnote/blob/master/docs/build.md).

However, it's bit complicated, so I build for linux-x64 system. You can download from [here](https://send.firefox.com/download/4b47987d80/#IV9_wZrOD_8vxi-_OAICpA).
**Caution: This file link will not valid after 1 download or in 24 hours.**

Yesterday, I reproduced your problem and I confirmed it has been fixed by my PR #1105.

Enjoy!

**Comment by karanrajpal14** [comment]
@yosmoc just downloaded your build and it worked. Thank you for doing that! Also, thank you for fixing the issue as well. I'll be closing this now since your fix will be merged eventually :)
