### ISSUE TITLE
Scroll bar does not work properly

### ISSUE THREAD

**Issue by zegui7** [BoostIO/Boostnote#1204]
Apart from the already reported non-active bar presence in most notes, I am having problems actually *using* the scroll bar - I click and drag and nothing happens. Scrolling has to be done mostly with my mousepad and pgup/pgdown which feels unpractical. 

I'm using BoostNote 0.8.17 in a Windows 10 

EDIT: Also, adding a "lock" mode to the markdown preview mode would be wonderful

**Comment by klingat** [comment]
I noticed some scrolling issues as well.

For example, when I am editing a note, and then click away from it to see the formatted note, the scroll simply does not work. I cannot scroll to the top of the note.

In order to be able to scroll again, I have to go to another note, and go back to my original one, and then the scroll works. 

But then the cycle restarts if I edit my note again and want to scroll to the top.

**Comment by Tykzz** [comment]
I have the same problem. Apart from switching notes, the scroll bar works again after resizing the window.

**Comment by janva255** [comment]
I have this problem too

**Comment by CicoZhang** [comment]
I have this problem too.
