### ISSUE TITLE
Symantec quarantines the windows exe on installation

### ISSUE THREAD

**Issue by andersab** [BoostIO/Boostnote#1248]
Symantec on Windows classifies your isntaller as an infected file.

![download](https://user-images.githubusercontent.com/931507/33664181-b991c750-da60-11e7-9ed5-30ee13277f5d.png)
![run](https://user-images.githubusercontent.com/931507/33664191-bf444682-da60-11e7-97a0-e14aeea64bf2.png)
![error](https://user-images.githubusercontent.com/931507/33664201-c9955e6e-da60-11e7-864b-efd23f6f91a5.png)
![quarantine_infections_report](https://user-images.githubusercontent.com/931507/33664206-cde909d4-da60-11e7-8be5-dfa5389fb469.png)

**Comment by kazup01** [comment]
Hi @andersab , thanks for your report.
This is not a problem of Boostnote, it is a feature of smartscreen in Windows.
Since we updated Windows app's certificate the other day, this warning is appearring now when download the Windows app, but it will be disappearred in sometime soon.
There is no security problem.
