### ISSUE TITLE
Checkbox inserted when there is already one

### ISSUE THREAD

**Issue by kparkov** [BoostIO/Boostnote#1265]
When pressing enter after a checkbox line, it inserts a new checkbox, which is fine. However, if I put the cursor at the start of a line **already containing a checkbox** and press enter, it inserts another checkbox. This makes it difficult to rearrange items.

![dec-09-2017 23-55-48](https://user-images.githubusercontent.com/805549/33800258-92445170-dd3c-11e7-981a-641b0a94b698.gif)

**Comment by AnastasiaDunbar** [comment]
This also happens with asterisks for bullet lists.

**Comment by mslourens** [comment]
The cause of this issue is in CodeMirror, not in BoostNote. It happens whenever you have those two brackets next to the bullet point, see this simple [Plunkr](https://plnkr.co/edit/H8B0FiTF4bdqroMWChpA?p=preview). I created an [issue](https://github.com/codemirror/CodeMirror/issues/5125) at CodeMirror for this. Let's see if they will pick it up.

**Comment by ZeroX-DG** [comment]
Can't reproduce this issue in the latest version. Maybe it's fixed. Please feel free to re-open this issue if it still exists.
