### ISSUE TITLE
Can't create new Note on Mac OSX El Capitan

### ISSUE THREAD

**Issue by kurohune538** [BoostIO/Boostnote#131]
I couldn't create new note with `command + N` or Tapping `+` button.
Once I uninstalled the app, then I re-installed. 
But it didn't work....

**Comment by Rokt33r** [comment]
I need more information.

Open console by pressing `Cmd + Alt + I`. There might be an error message.
And, take a screenshot of it.

**Comment by Venox** [comment]
Same error but in Windows.

The console error is this:
main.js:14 Uncaught Error: No folder to craete a note.
![image](https://cloud.githubusercontent.com/assets/14144989/19028605/f0610758-8978-11e6-939e-245927ef1c91.png)

It happened after I removed all storage folders and then created a new one.
Reinstalling the app also doesn't solve the problem.

**Comment by Rokt33r** [comment]
@Venox 

In your case, It is not a bug. Just add a storage and create a folder.

<img width="542" alt="screen shot 2016-10-03 at 3 00 46 pm" src="https://cloud.githubusercontent.com/assets/5865853/19028714/33b7df58-897a-11e6-9dc2-aebe79014973.png">

Hmm.. I think I should provide a unremovable storage which uses app cache. The app without any storages actually is inability.

**Comment by Venox** [comment]
Thank you Rokt33r

I actually got confused, I though I was adding a storage but I was adding a folder without having a storage (not sure if that is intended to be possible).
I was able to add the storage and now bot, the "Create note" button and Cntrl+N work again,

Would be nice if instead of throwing an error to Console, when this happens, a pop-up like "You have to have an storage to create notes" would be shown.

Again, thanks and keep it up!

**Comment by Rokt33r** [comment]
@Venox Yes, it should be as you said. Thanks for your feedback!
