### ISSUE TITLE
Show confirmation dialog when deleting a note

### ISSUE THREAD

**Issue by mslourens** [BoostIO/Boostnote#1320]
When a note is deleted by pressing the delete button on the right, the note is deleted directly, without any confirmation dialog.  It is generally good to confirm deletions or any destructive changes, as mentioned in this #1317. 
We should add an option in the preferences dialog to disable this feature.

**Comment by sosukesuzuki** [comment]
When you delete a note, it enters Trashed.
Also, you can restore it, and if you delete note from Trashed, Boostnote shows alert.
<img width="421" alt="2017-12-22 00 11 13" src="https://user-images.githubusercontent.com/14838850/34261514-adc0c34c-e6ac-11e7-8eeb-92547040ec73.png">
So, I think dialog when deleting a note is unnecessary.

**Comment by mslourens** [comment]
I know that, but we discussed it in #1317, saying that removing file to the trash in the OS also shows a warning, the same as emptying the trash. Now we just show the warning when permanent removing the file from the trash. So you think we should not implement this?

Just a general question: Who is the product owner of Boostnote and decides which feature requests are going to be implemented?

**Comment by sferra** [comment]
sincerely, i initially didn't notice that there is a "Trash" so when i first accidentaly deleted a note i panicked until i found the "Trash" can. in the meantime i know there is a "Trash", but it is still annoying to trash stuff accidentally.

informing the user that something will be discarded is simply good practice. generally file managers will also warn you if you delete a file, even if it can be found in a "trash can" later. since we should be able to disable the prompt for "power users", there is no reason **not** to implement the behavior, or at least to consider iot.

@mslourens i think that would be @kazup01 but i might be wrong.

**Comment by sosukesuzuki** [comment]
I see.
Certainly, this feature is necessary.

@mslourens @sferra Product owner is @kazup01 .

**Comment by kazup01** [comment]
We will merge #1324. Wait a moment.

**Comment by chiangs** [comment]
Just another thought, in gmail when you delete something, a popup just says it's been moved to the trash with an option to undo...maybe smoother than a confirmation popup?

**Comment by sferra** [comment]
@chiangs i also thought about that. i think it's a good idea, but then it would make sense to make the "[snackbar](https://material.io/guidelines/components/snackbars-toasts.html#snackbars-toasts-usage)" functionality generally available in boost note, not just for this single use case. i would suggest opening a new issue for that.

i think its a good thing to have the dialog in place first and improve from there on ;)

**Comment by sosukesuzuki** [comment]
This issue was fixed from #1324 . And, #1324 was merged!!
