### ISSUE TITLE
Help for Dockerize Boostnote

### ISSUE THREAD

**Issue by SkYNewZ** [BoostIO/Boostnote#1345]
Good morning!
First of all, thank you very much for this wonderful app! Being a big fan of Docker, I'd like to "dockerize" your application since it doesn't exist on the [Docker Hub](https://hub.docker.com/), and I'd like to make it official afterwards and propose it to you. If I'm not mistaken I can see that your application is a web app, could you help me to launch it in web format, visible in a browser? Thank you in advance. [SkYNewZ](https://github.com/SkYNewZ)

**Comment by Rokt33r** [comment]
We're going to provide it a little different way.

Actually we can do it now. But, the client app won't detect any changes made by others. So, the user should refresh the app page to grab the changes.

**Comment by SkYNewZ** [comment]
Okay, thanks for the answer. Don't hesitate to keep me informed :) Good end of day!

**Comment by mapaiva** [comment]
Hey guys,

I'd like to respectfully introduce an input on that. I'm using fedora and since there's no official `rpm` package available (at least there wasn't the last time I've tried) I made some effort to have the boostnote app dockerized. Here's the result https://hub.docker.com/r/mapaiva/boostnote/.

It's running smoothly so far. However, the issue mentioned by @Rokt33r is there. No update grabbing is being automatically handled  😞 . But as a step-solution, it just works :)
