### ISSUE TITLE
Integer of 7 digits or more is forcibly highlighted

### ISSUE THREAD

**Issue by cignoir** [BoostIO/Boostnote#1378]
HI, I'm running ver 0.8.19 on Win10 64bit.

![d2443047fc5844bacec5a6a1f5926522](https://user-images.githubusercontent.com/247498/34758284-a68c99c6-f619-11e7-9da7-33da5e8ce213.png)

**Comment by cignoir** [comment]
The highlight was canceled when it exceeds 40 digits.

![a42877cfeaad69ff64f9ed9ce3003e44](https://user-images.githubusercontent.com/247498/34815752-edbfadd8-f6f5-11e7-93ba-a10e153e1185.png)

**Comment by sosukesuzuki** [comment]
hi, @cignoir. Markdown editor of Boostnote is depend on [CodeMirror](https://github.com/codemirror/CodeMirror). And, it's highlighting is depend on [ghm mode](https://github.com/codemirror/CodeMirror/blob/master/mode/gfm/gfm.js). Also, may be, [this Line](https://github.com/codemirror/CodeMirror/blob/master/mode/gfm/gfm.js#L84) cause your issue. I think your issue is not bug.
