### ISSUE TITLE
[Feature request] Edit note title

### ISSUE THREAD

**Issue by myxo** [BoostIO/Boostnote#1415]
Hello.
Right now markdown note title is basically the first line of note content.
My suggestion is to separate title from content and make title editable.

Current solution make documents a bit more messy.

**Comment by ItsPugle** [comment]
I'd love to see this - especially with the Snippet Notes. Sometimes I want to explain more as to what the snippet does while still maintaining a succinct title.

**Comment by glego** [comment]
Personally I needed to adapt to this change as well. But I actually like this because it forces you to give a good descriptive title and will be consistent across the whole note (e.g. when exporting ect...).

I don't use the snippet function (yet?) But if it is required for some I suggest to keep the title optional and take the first line when it's empty. 

Cheers,
Glenn

**Comment by glego** [comment]
Personally I needed to adapt to this change as well. But I actually like this because it forces you to give a good descriptive title and will be consistent across the whole note (e.g. when exporting ect...).

I don't use the snippet function (yet?) But if it is required for some I suggest to keep the title optional and take the first line when it's empty. 

Cheers,
Glenn

**Comment by breaker0101** [comment]
hi i'v found  a way to do that : go to boostnote folder then note folder you are going to see a liste of notes..open them in any text editor..and edit the title..restart the app to see the changes.

**Comment by ZeroX-DG** [comment]
From v0.11.11 you can specify the note title using the front matter:
```md
---
title: Custom note title
---

Just a test note
```
I'll close this issue.

**Comment by BrwnBearz** [comment]
![boostNote_title](https://user-images.githubusercontent.com/4138707/74461797-bb9bf100-4e54-11ea-8601-da190e9abeb1.png)
@ZeroX-DG thanks for the additional information on custom titles for notes!
unfortunately, it doesnt seem to be working for me. I might be doing something wrong, but i am copyxpasting from your post above and i still get an "empty note" title.
any assistance here would be greatly appreciated. thanks in advance!

**Comment by BrwnBearz** [comment]
@ZeroX-DG problem solved!
sorry, i misread one of your previous post on this matter. I expected the front matter title to work after _unchecking_ the option for 'extract title from front matter'.
apologies for the confusion. I've only just discovered this app, but its perfect for all my note taking needs. thanks for all your hard work! :)
