### ISSUE TITLE
Ability to sync notes with evernote

### ISSUE THREAD

**Issue by ishu3101** [BoostIO/Boostnote#15]
Thank you for making this awesome notetaking app for programmers. I would love to be able to sync notes with evernote.

**Comment by Rokt33r** [comment]
Please check this issue. Currently, It's hard to implement that feature because of its development cost.
https://github.com/BoostIO/Boostnote/issues/9

But, If you really want it and you can afford to spend time with me, it would be possible. :)
(You can teach me how to sync or find related posts and some examples on the internet)

**Comment by Rokt33r** [comment]
Please reopen this issue when you are ready to help me or still have some questions.

**Comment by ishu3101** [comment]
What about the ability to import from and export to evernote?

**Comment by Rokt33r** [comment]
Those two ability will be implemented!

**Comment by ishu3101** [comment]
When are they coming to Boostnote?

**Comment by Rokt33r** [comment]
It would take a month I thought. Because I have to finish v0.6.0 first.
