### ISSUE TITLE
Markdown in Snippet Note: Toggle Button

### ISSUE THREAD

**Issue by tatoosh** [BoostIO/Boostnote#1504]
In the Snippet Note with Markdown Syntax the toggle button is missing like in normal markdown notes:

![grafik](https://user-images.githubusercontent.com/3670907/35782900-c3d2f878-09ff-11e8-9132-fb7625f09435.png)

![grafik](https://user-images.githubusercontent.com/3670907/35782916-fcc57caa-09ff-11e8-8e96-e37b4823462e.png)

Tested on boostnote v0.9.0 windows 10

**Comment by islanddog** [comment]
I believe Snippet Notes are not meant to feature a 'Toggle' button because they are meant to be just Snippets.

![image](https://user-images.githubusercontent.com/16761753/35808342-7301f094-0a53-11e8-87cb-526251c20c46.png)

You can utilize the dropdowns at the bottom of Snippet notes for Syntax or utilize the Markdown notes for Markdown specific notes.

![image](https://user-images.githubusercontent.com/16761753/35808441-c798493c-0a53-11e8-978f-91c6af77e8e4.png)

**Comment by tatoosh** [comment]
I am using the first snippet always as markdown documentation, so the toggle should be nice at markdown Syntax.

**Comment by Flexo013** [comment]
Snippet notes are not intended for this preview feature.

@tatoosh For what reason are you choosing a Snippet note with Markdown syntax over just a Markdown note?

**Comment by Flexo013** [comment]
I'm closing this issue do to prolonged inactivity.

If you still are experiencing this problem then feel free to reopen this issue or create a new issue with all the relevant information.
