### ISSUE TITLE
[Feature Request] Encryption

### ISSUE THREAD

**Issue by islanddog** [BoostIO/Boostnote#1511]
First off I would like to state how much I have enjoyed seeing Bootnote progress over the past 6 months of me using it. I currently utilize Sublime Text in tandem with Boostnote and find myself referring to Sublime less and less everyday. I think adding a password to lock files or storage would be a great idea to provide some security on both sides.

Thanks

**Comment by tatoosh** [comment]
if there will be an option for encryption the mobile app also need it!

**Comment by ikelaiah** [comment]
You could use Boostnotes in conjunction with Sync.com or pCloud.com.

**Comment by ericchang00** [comment]
@islanddog Are you using Boostnote as a text editor?

**Comment by islanddog** [comment]
@ericchang00 - For writing technical documentation with coding notes yes. The company I work for does not allow data to leave site so having the ability to encrypt files/storage would allow my personal code to stay confidential in the event if I leave or someone accesses my computer.

**Comment by ericchang00** [comment]
Sweet, that's a really cool use case!

**Comment by islanddog** [comment]
@ericchang00 - Yes, I currently need to utilize Transcrypt which I have built into Sublime Text and then decrypt every morning. Would be nice if a simple password and encryption method was used per-storage in BoostNote as doing this with multiple document points can get tedious.

**Comment by solariz** [comment]
Same here, currently I can use boost only without the sync because of policy I cant put in work documents to cloud providers other than the company internal ones and privately i do not want to store any personal data on google drive or similar.

I switched from boost now to another app named Joplin also open source available on github. But the features I lack from boost are to many to stay with it. So a midterm E2EE support would be very nice.

**Comment by D0048** [comment]
Same here. Having encrypted sync allows me to sync the notes to clouds like dropbox.

**Comment by alexanderadam** [comment]
I think this is now the fourth issue for encryption and I have the feeling it would be better to have just one. It seems that @chartotu19 started working on it and you can track it on #827.

**Comment by the-paulus** [comment]
I would love to see Boost be capable of encrypting its data as well. In the mean time, what I currently do is use an encrypted loopback filesystem. For this I use [VeraCrypt](https://www.veracrypt.fr) because dm-crypt can open VeraCrypt volumes. For the average user [Cryptomator](https://cryptomator.org/) would be a better choice for them since it is pretty simple to use.

**Comment by Flexo013** [comment]
Duplicate of #827
