### ISSUE TITLE
Spaces after apostrophes when viewing a note

### ISSUE THREAD

**Issue by Je4hel** [BoostIO/Boostnote#155]
**Reproduction steps**
1. Create a Markdown note
2. Type some text containing apostrophes in the note content
3. Switch to view mode (click outside the editor)

**Expected result**
The text is rendered normally.

**Observed result**
Every apostrophes are followed by a large space in certain cases.

**Screenshots**
_Edit mode_
![image](https://cloud.githubusercontent.com/assets/5781642/19485529/b68f020c-955b-11e6-9e5f-0a42b52d6c89.png)

_View mode_
![image](https://cloud.githubusercontent.com/assets/5781642/19485603/d1ac170a-955b-11e6-95cb-3ce31f9b5d63.png)

**Remarks**
I am French, the apostrophe is not used for quoting content but it is very common between words (like the possessive mark in English). I add this remark because there seems not to be a problem when the apostrophe is used to quote content (see the "toto le haricot" part of the text in the captures) but in French, it is never used like that (we use double quotes) so this is very problematic for at least the French language.

**Comment by Rokt33r** [comment]
Thanks for reporting. I'm currently investigating it now. I'll inform you later.

**Comment by Rokt33r** [comment]
![screen shot 2016-10-24 at 6 37 26 pm](https://cloud.githubusercontent.com/assets/5865853/19640715/f541f650-9a18-11e6-9167-8bbc55f1b662.png)
![screen shot 2016-10-24 at 6 37 28 pm](https://cloud.githubusercontent.com/assets/5865853/19640716/f55332ee-9a18-11e6-942d-4edc4dc33a5f.png)

It works fine on OS X. I'll inform you after I try it on Windows.

**Comment by mikeres0** [comment]
@Rokt33r the bug is present on Windows 10

**Comment by mikeres0** [comment]
The `.cson` file is saved correctly so I think it's something to do with viewing the note

**Comment by mikeres0** [comment]
The ' is actually being rendered as an apostrophe followed by a blank space which is odd...

**Comment by Rokt33r** [comment]
<img width="800" alt="2016-10-30" src="https://cloud.githubusercontent.com/assets/5865853/19831710/c96ad27c-9e4b-11e6-8fbf-6004c1f33a7c.png">
<img width="800" alt="2016-10-30 1" src="https://cloud.githubusercontent.com/assets/5865853/19831711/c9912d78-9e4b-11e6-90e9-33d1fd2e9d3a.png">

Sorry for being late. My windows PC had been broken. So I had to reinstall OS.
Anyway, I'm failed to reproduce this problem... Could you give me more information?

**Comment by julianmaster** [comment]
Same error with Windows 10 and Boostnote 0.7.2
Write in markdown :
![capture1](https://cloud.githubusercontent.com/assets/1508942/20933485/7a7155f6-bbd8-11e6-8003-6c263541e4a3.PNG)

Result :
![capture2](https://cloud.githubusercontent.com/assets/1508942/20933486/7a725474-bbd8-11e6-94c3-afead11b69d0.PNG)

**Comment by lawgsy** [comment]
I can reproduce and confirm this, I found this issue upon searching for this behaviour myself. I'm on Windows 10, Boostnote v0.8.0 (latest binaries at the time of writing this).

Additional information:
Upon selecting the text character by character in the rendered markdown, the apostrophe and space are selected as one single symbol (as if it were one character), rather than selecting the apostrophe and space separately. Must be a rendering issue of some sort.

**Comment by tex1337** [comment]
I can also reproduce this, and have found a fix for myself personally.

I believe this is written in express, which means that there is probably some issue with the fonts provided with the editor as when I changed mine to hack.ttf or any other font, the issue was resolved immediately.

Perhaps a dodgy font file or just requiring the inclusion of a correct text encoding?

Hope this helps!

_Editor View_
![image](https://user-images.githubusercontent.com/5818550/26858669-8ce79b78-4b2a-11e7-8933-8d20740a7da2.png)

_Preview View_
![image](https://user-images.githubusercontent.com/5818550/26858698-b6496cd0-4b2a-11e7-824d-9ec46599c60d.png)

**Comment by oleksandrzelentsov** [comment]
it still is in place if anything, Win 10

**Comment by asmsuechan** [comment]
@oleksandrzelentsov I'm going to try fixing it in a few days.

**Comment by asmsuechan** [comment]
What you can do to fix this issue is set `Segoe UI` as your Font Family from `Menu` -> `UI`.

**Comment by oleksandrzelentsov** [comment]
okay, thank you

2017-07-25 7:16 GMT+02:00 SuenagaRyota <notifications@github.com>:
