### ISSUE TITLE
Fix test

### ISSUE THREAD

**Issue by Rokt33r** [BoostIO/Boostnote#1562]
For now, some of tests of Boostnote have been failling randomly. I think it is because mocking `localStorage` isn't done properly.

**Comment by pfftdammitchris** [comment]
I'm looking at the test files and some of them are checking only for "null" types when they create mock storage . This seems to be creating a lot of "undefined" values if we aren't checking for other falsy values (the tests seem to be failing due to undefined types)

The reorderFolder-test is failing checks, showing that prop "key" cannot be read from "undefined".
When I checked back, the createFolder-test created the beginning storage with **TestDummy.dummyStorage(storagePath)**
When we look at TestDummy.dummyStorage function, there is a second argument which defaults to an empty object. This looks fine so far but look what happens in the function:

```
function dummyStorage (storagePath, override = {}) {
  var jsonData = override.json != null
    ? override.json
    : dummyBoostnoteJSONData()
  var cacheData = override.cache != null
    ? override.cache
    : {}
  if (cacheData.key == null) cacheData.key = keygen()
  if (cacheData.name == null) cacheData.name = faker.random.word()
  if (cacheData.type == null) cacheData.type = 'FILESYSTEM'
  cacheData.path = storagePath

  sander.writeFileSync(path.join(storagePath, 'boostnote.json'), JSON.stringify(jsonData))
  var notesData = []
  var noteCount = Math.floor((Math.random() * 15)) + 1
  for (var i = 0; i < noteCount; i++) {
    var key = keygen()
    while (notesData.some((note) => note.key === key)) {
      key = keygen()
    }

    var noteData = dummyNote({
      key,
      folder: jsonData.folders[Math.floor(Math.random() * jsonData.folders.length)].key
    })

    notesData.push(noteData)
  }
  notesData.forEach(function saveNoteCSON (note) {
    CSON.writeFileSync(path.join(storagePath, 'notes', note.key + '.cson'), _.omit(note, ['key']))
  })

  return {
    json: jsonData,
    cache: cacheData,
    notes: notesData
  }
}
```

When **cacheData** is being declared, override.cache can be undefined (since we just defaulted to an empty object) but still passes the **null** check and is **assigned undefined** when its supposed to fallback to an empty object

```
var cacheData = override.cache != null
    ? override.cache
    : {}
```

In the end the dummyStorage returns an object with prop "cache" which is now undefined, when we go back to reorderFolder.test it seems to fail at this line const storageKey = t.context.storage.cache.key

Which seems to be something like this:

![image](https://user-images.githubusercontent.com/20717348/36643903-cd4ea4da-1a06-11e8-8b58-bbb1bb0d6f01.png)


If these incomplete checks are what makes the test fail, shouldn't we test for _all_ falsy values including undefined? (And probably use a === check instead of == to be safe)

**Comment by rayou** [comment]
At lease two dummy folders are required for reordering a folder. Current dummy data implementation might result in only one folder generated. Please see code below.

[TestDummy.js](https://github.com/BoostIO/Boostnote/blob/master/tests/fixtures/TestDummy.js#L25)
```js
var folderCount = Math.floor((Math.random() * 5)) + 1
```

[reorderFolder-test.js](https://github.com/BoostIO/Boostnote/blob/master/tests/dataApi/reorderFolder-test.js#L27)
```js
  const secondFolderKey = t.context.storage.json.folders[1].key
```

I'll put up a PR later when I am available if there's no one fix this :P. Happy Friday!
