### ISSUE TITLE
Web App

### ISSUE THREAD

**Issue by ishu3101** [BoostIO/Boostnote#17]
Are there any plans for having a web app for Boostnote so that you can access & create your notes online from any device like in Evernote?

**Comment by Rokt33r** [comment]
All data will be stored as a file in any directory. It means you will be able to share your note by just set the directory in Google drive or Dropbox. 
But, I don't have a plan to provide cloud server currently. (Maybe I make a server app for dedicated server.)

About the web app, I think I should imitate the way of [stackedit](https://stackedit.io/) because we have no cloud.

**Comment by Rokt33r** [comment]
It depends on OS.

OS X
```
/Users/$USER_NAME$/Library/Application Support/boost/local.json
```

Windows
```
C:\Users\$USER_NAME$\AppData\Roaming\boost\local.json
```

**Comment by ishu3101** [comment]
Cheers. You should add this information to the README.md

**Comment by Rokt33r** [comment]
I agree with it.

**Comment by Rokt33r** [comment]
I added it to readme.md. Please reopen this issue if you have more question about it. :)
