### ISSUE TITLE
Tags not escape on exporting to .html

### ISSUE THREAD

**Issue by hos2002820** [BoostIO/Boostnote#1728]
If my content has tags something like
```
<br>
```
or
```
<VirtualHost *:80>
</VirtualHost>
```

they will not show on exported .html

**Comment by nlopin** [comment]
@Rokt33r put it on me

**Comment by Rokt33r** [comment]
@nlopin Gladly. 👍 👍 👍

**Comment by Bubka** [comment]
Hello,
The PR #1753 broke correct display of quotes in Mark Down Frames (4 spaces as line prefix)

my MD code:
```
    "}, "2":{"
```

The html exported code is:
```
<code>
    &quot;}, &quot;2&quot;:{&quot;
</code>
```

So in the browser it's looks like:
![image](https://user-images.githubusercontent.com/858858/38861585-33bce412-4233-11e8-866a-2bc1eaa320fb.png)

instead of:
![image](https://user-images.githubusercontent.com/858858/38861534-12263826-4233-11e8-8f45-39d81f0d0185.png)
like it used to work
