### ISSUE TITLE
link in markdown preview does not work, gives empty page

### ISSUE THREAD

**Issue by wangsen992** [BoostIO/Boostnote#1856]
# Current behavior
The link in markdown preview mode does not work. When I clicked it, the previous markdown page is replaced with a blank page, and then nothing happens. 
So if I use the "Welcome to Boostnote!" note as an example, this is what I have before clicking any link, 
![before](https://user-images.githubusercontent.com/6318958/39086503-43a76764-4560-11e8-84da-12dc0614333f.png)

And after clicking any link, I get this, 
![after](https://user-images.githubusercontent.com/6318958/39086504-46ce9d18-4560-11e8-8051-900de5c2a3ce.png)
![errors](https://user-images.githubusercontent.com/6318958/39086750-03d06578-4565-11e8-80f2-0a3f79aa8043.png)
I am not sure what the cognito-identity error is, but it shows up as along as I am using the app. The _Refused to display_  error appears right after I click any link, and it will get quickly buried by the _congito-identity_ thing. 

The behavior persists with link to other notes as well. I have tried to restart the chrome after running `sudo apt-get update` and `sudo apt-get upgrade`. The current boostnote version is 0.11.4 and my OS is Ubuntu 16.04. 

# Expected behavior
I will expect that it will jump to other note if it is an internal link to another note and pop up a new tab in a browser if it is an external link. 

# Steps to reproduce

1. Simply use this version and click any link. 

# Environment

- Version : 0.11.4
- OS Version and name : Ubuntu 16.04

**Comment by ZeroX-DG** [comment]
Basically why this bug occur is because when you click on a link, boostnote will load that specific page in an `iframe` tag. However, in this case, the website that you need to load doesn't allow `iframe` to load it due to security reason which is a type of attack called `clickjacking`. I'm busy at the moment but I think changing iframe to [webview](https://electronjs.org/docs/api/webview-tag) can solve the problem, if you can then submit a PR for this issue
