### ISSUE TITLE
What is the current state of Boostnote?

### ISSUE THREAD

**Issue by tejado** [BoostIO/Boostnote#189]
@kazup01 and @sota1235
As far as I can see, there is currently no real activity by you, the official maintainers.
What is the current state of the project (e.g. is it abandoned by you?) and what is planned for the future?

Thanks!

**Comment by amlcodes** [comment]
They just released a new version 8 hours ago? There is a wait list for a team version. Features are being polished and added.

**Comment by tejado** [comment]
Hm, sorry but in my opinion the repo activitiy is currently lower than it was before with Rokt33r.
And as the maintainer changed, it would be great to get some info to which the app is heading as also a lot of current issues were not answered, including the project page. It is just for info, that we know Boostnote is still maintained.
The wait list for the team version is also not really new...

**Comment by mikeres0** [comment]
Yeah it's a lot lower... This project seems in complete disarray. A few weeks ago there was talk of completely scrapping Boostnote and rebuilding it from scratch. The team version has been promised for months now, it is certainly not new. Any comments to add, maintainers/

**Comment by kazup01** [comment]
Thank you for comments.
I'm really sorry for the confusion.

Since maintainer Rokt33r retired from the company at the end of November, we were rearranging the team.
The new maintainer has been decided to @sota1235  and we started working.

We will respond to unsolved issues from now.
I'm sorry to have kept them waiting so long.

Most importantly, Boostnote will continue and improve in the future.
Our team wants to make Boostnote better for users all over the world.

We are currently preferentially updating the design, and we plan to release it at the end of Dec or early Jan.
In addition, Boostnote Team has been delayed in development, but we are going to release in the next Feb or Mar.

I apologize again for causing confusion.
I am poor at English but I'll do my best.

If have any questions or advice, please talk to me or @sota1235 .

Thank you!

**Comment by kazup01** [comment]
We(me and @sota1235 ) have no experience of operating the OSS community.
However, we want to operate the community sincerely.

If possible, We would like to hear your opinion about the community operating.
If you are me, what kind of action would you take about it?

Please teach to us.

Thank you.
