### ISSUE TITLE
My vision on Boostnote and ideas to improve

### ISSUE THREAD

**Issue by brpaz** [BoostIO/Boostnote#197]
Hello.
Right now, I am using Boostnote almost everyday as my primary note taking app, and I really like it. Still, a lot of things to improve.

Here are the improvements I consider most important from my daily usage. some of then where already suggested. 

 **Tags list and filter** 

Maybe like quiver (http://happenapps.com/#quiver with a button to toggle between notebooks and tags in the sidebar. 
Some users might prefer to use tags, other folders or even combine then. I would like love to be able to take the best from the tags feature.

**Change order of folders and storage / star entire folders.** #194 

Maybe the most needed feature for me.
Right now, I have more than 20 folders. Since they dont have any specific order, its really hard to find the folder I want. This could be improved if they are ordered alphabetically by default for example and then allow user to reorder then, 
Also it would be great if we can star a folder and it would appear after the "starred" item in the menu.

 **Menubar app**  #58

Could work like Snippets Lab assistant: https://www.renfei.org/snippets-lab/) where you can easily search and create new notes) from the menubar.
Finder as a similar functionality but myself I would prefer to also have the menubar.

Right now, I am using  [snippet-bar](https://github.com/teesloane/snippet-bar) for quick snippets that I need to use frequently (like bash commands etc) and Boostnote for more complex snippets and notes. It would be great to use the same app for both.

**Move folders between storages**

* Using drag-and-drop for example?

**Design improvements**

I am enjoying to see @sota1235 redesign. I is looking much better. Just continue that way,

some extra suggestions:
* Add more space between storages. Everything looks like a long list. its hard to differentiate.

Thank you and continue the excellent work. With this features, Boostnote would be perfect, :)

**Comment by kazup01** [comment]
Hi brpaz san,
I'm sorry to late.
Thank you for using Boostnote and great feedback!
We're very glad about it.

Please check below.

**1, Tags list and filter**
Quiver is nice app.Certainly, tag management is weak in Boostnote.
We improve based on your feedback.

**2, Change order of folders and storage / star entire folders.** #194
Very good idea.
I have more than 20 folders too, I want Folder's reorder and star function.
I think I have to improve more this UX, too. Thank you for your feedback!

**3, Menubar app** #58
Snippets Lab is looks good.
We were being considered search and post from Menu-bar, but we were postponed because of the improvement of the core function.
The way to use your snnipet-bar is very helpful.
We'll consider about it continuously!

**4, Move folders between storages**
I think so too! We will improve it.

**5, Design improvements**
We just updated new design a short while ago!
Let's enjoy it :)


I'm really thankful to your feedback!
I am looking forward to your feedback again :)

**Comment by kazup01** [comment]
Hi @brpaz , we added many features of the above list. If you have any feature requests, please make that Issue. Thank you for your help!
