### ISSUE TITLE
Do you have Atom's one dark theme? I love it!!!! please add it to Boostnote,thanks

### ISSUE THREAD

**Issue by leasin** [BoostIO/Boostnote#1998]
Do you have Atom's one dark theme? I love it!!!! please add it to Boostnote,thanksDo you have Atom's one dark theme? I love it!!!! please add it to Boostnote,thanks

**Comment by yougotwill** [comment]
Great idea I'm also a fan of one dark! :)

Quick workaround that you can do for now.
Download this https://github.com/Aerobird98/codemirror-one-dark-theme 
On macOS you can copy the .css file into the app directly in `/Contents/Resources/app/node_modules/codemirror/theme` not sure about windows or linux but I assume it is similar.

@Rokt33r @kazup01 Are we allowed to merge that repo into the existing BoostNote themes?

**Comment by prydda** [comment]
This is only for the editor theme, is it possible to add this as interface theme?

**Comment by Rokt33r** [comment]
@yougotwill I think it's fine. Sorry for the late answer.

**Comment by Maxxiii** [comment]
@yougotwill Thank you, works great for Windows too (C:\Users\[USER]\AppData\Local\boost\app-0.15.1\resources\app\node_modules\codemirror\theme)
The only thing I fixed in this css - is removed font-weight and font-size properties from the beginning of the file, so font would have correct default size.
