### ISSUE TITLE
Could you add Idle Fingers as an editor theme?

### ISSUE THREAD

**Issue by Ocanamat** [BoostIO/Boostnote#200]
Hi Devs!

Great little piece of code you have here, I am using it to build up my R code library. Small feature request, could you add IdleFingers as an editor color theme?

http://colorsublime.com/theme/idleFingers

Would be happy to help if needed. 

Regards,

**Comment by kazup01** [comment]
Hi Ocanamat san!
Thank you for your suggesting. If possible, would you send us to a pull request?

**Comment by asmsuechan** [comment]
@Ocanamat The easiest way for now is to put `idlefingers.css` (like [this](https://github.com/FarhadG/code-mirror-themes/blob/master/themes/idlefingers.css)) in `./node_modules/codemirror/theme/`.

**Comment by asmsuechan** [comment]
Hi @Ocanamat, we cannot add our own theme easily to Boostnote because Boostnote references the default theme of codemirror directly e.g. [here](https://github.com/BoostIO/Boostnote/blob/master/browser/lib/consts.js#L7).

If you'd love to really use IdleFingers theme, there is a way only to change local app instead of throw a PR (ofcourse it's not a good way).

1. Download idlefingers.css e.g. [this](https://github.com/FarhadG/code-mirror-themes/blob/master/themes/idlefingers.css)
2. Find your Boostnote directory (on mac,  it's `/Applications/Boostnote.app`)
3. Copy idlefingers.css to theme directory by the command below:
```
$ cp idlefingers.css /Applications/Boostnote.app/Contents/Resources/app/node_modules/codemirror/theme/
```
4. Configure the theme from Menue -> UI -> Theme

That's it.

![2017-01-11 21 13 42](https://cloud.githubusercontent.com/assets/11307908/21848135/e3b08fb0-d842-11e6-8e0e-123d56ae2498.png)

**Comment by asmsuechan** [comment]
Any questions? If nothing, please close this issue. I'll close this in under 3 days unless you react.

**Comment by amyth-singh** [comment]
can you add this theme to VSCode?

**Comment by Kikkervelf** [comment]
> can you add this theme to VSCode?

You can simply add the following to settings.json and that will give you the Idle Fingers theme:

```
{
    "editor.fontSize": 17,
    "workbench.colorTheme": "Default Positron Dark",
    "editor.fontVariations": false,
    "workbench.colorCustomizations": {
            "editor.background": "#323232"
    },
    "editor.bracketPairColorization.enabled": false,
    "editor.tokenColorCustomizations": {
        "comments": "#bc9458",
        "strings": "#a5c261",
        "numbers": "#6892b2",
        "keywords": "#cc7833",
        "functions": "#ffffff",
        "variables": "#ffffff",
        "textMateRules": [{
            "scope": "punctuation",
            "settings": {
                "foreground": "#6892b2"
            }
        }]
    }
}
```
