### ISSUE TITLE
Old URL exists in the source

### ISSUE THREAD

**Issue by re-fort** [BoostIO/Boostnote#202]
ドキュメント・ソース中で旧URL(https://b00st.io/)
を参照している箇所が存在します。
https://github.com/BoostIO/Boostnote/search?utf8=%E2%9C%93&q=https%3A%2F%2Fb00st.io%2F

新URL(http://boostnote.io/)
に直したものをプルリクで送ろうと思いましたが、
[api.js](https://github.com/BoostIO/Boostnote/blob/2a6a2694d4318fdf1d26597206ed9d7fecc93fd7/browser/lib/api.js#L11)の修正方針がわからなかったので、とりあえずissueを立てておきます！

**Comment by kazup01** [comment]
現在旧urlの反映待ちですので、もう少しで復活すると思われますm(_ _)m
ご報告頂きありがとうございます！

**Comment by mikeres0** [comment]
Is it possible for this to be translated to English? (Even roughly) 👍 

Thanks in advance guys.

**Comment by kazup01** [comment]
@re-fort san,
こちらの方で後日新url(boostnote.io)に変更しておきますね！新デザインは如何でしょうか..？こちらのフィードバック等もお待ちしております👏

@mikeres0 san,
Thank you for your message!
re-fort san said old-url(https://b00st.io/) is  referred to in the document sauce. 
He created this issue because he tried to sent pull request that change to new-url(http://boostnote.io)  , but couldn't understand the correction policy of api.js.
So we will change it later.

**Comment by sota1235** [comment]
I will merge [this pull request](https://github.com/BoostIO/Boostnote/pull/206) after renew the URL of official page.
And release this fix next release. 
Wait a moment please!
