### ISSUE TITLE
Include sort order along with sortby

### ISSUE THREAD

**Issue by saratchandrakarumuri** [BoostIO/Boostnote#2037]
# Current behavior

Currently we only have option to sortby categories. It is good to add sort order also (ascending/descending). 

# Environment

- Version : 0.11.5
- OS Version and name : Windows 10 , mac

**Comment by jat255** [comment]
:+1: 

This is an important addition. In my use case, I write my notes with the date it was originally taken, it would be nice to be able to have most-recently created at the top, instead of at the bottom (I'm aware of the "updated" sort mode, but sometimes I update old notes and I still want them sorted in the order I originally created.

**Comment by Flexo013** [comment]
This is present in version 0.15.3 of Boostnote Legacy.
