### ISSUE TITLE
Clicking on info button displays info box on top of the button, making it difficult to hide the info box

### ISSUE THREAD

**Issue by bhrd** [BoostIO/Boostnote#2043]
# Current behavior
When clicking on ⓘ for info on the note, the info box opens up on top of the button itself. This makes it difficult to hide the info box easily, and makes how to hide, unclear.

![image](https://user-images.githubusercontent.com/221584/41128557-6f278392-6a63-11e8-90c7-7f48ce6c7894.png)

![image](https://user-images.githubusercontent.com/221584/41128545-65ca2516-6a63-11e8-9898-ae246773e7d0.png)

# Expected behavior
Box should be displayed below the button, instead of on top of the button

# Steps to reproduce

1. Open note
2. Click on ⓘ 

# Environment

- Version : 0.11.5
- OS Version and name : Mac OS Sierra

**Comment by yougotwill** [comment]
@bhrd Fixed :) https://github.com/BoostIO/Boostnote/pull/2075

**Comment by modmod24** [comment]
can you please re-open the issue? info box is still on top of button. 

**Current behavior**
-----
When clicking on ⓘ for info on a note in the Trash, the info box opens up on top of the button itself. This makes it difficult to hide the info box easily, and makes how to hide, unclear.

**Expected behavior**
-----
Box should be displayed below the button, instead of on top of the button

**Steps to reproduce**
1. Open note
2. Click on Trash
3. Select deleted note (found in Trash)
4. Click on ⓘ

**Environment**
-----
    Version : 0.11.7
    OS Version and name : Ubuntu 16.04.4

**Comment by modmod24** [comment]
@yougotwill, can you apply same fix for the Trash? There info button is still covered.

**Comment by yougotwill** [comment]
Sure will look into it this weekend!

**Comment by yougotwill** [comment]
@modmod24 Would you mind sending me a screenshot please? I'm using 0.11.7 and can't see the issue. Thanks :)

**Comment by modmod24** [comment]
sure, I recorded it:
[https://i.imgur.com/3xAbmaK.gifv](https://i.imgur.com/3xAbmaK.gifv)

too bad I don't know how to embedd it here :(

thanks for having a look into this :+1: 

this was recorded on windows, 0.11.7

**Comment by yougotwill** [comment]
Hey @modmod24 sorry it took so long to fix but see here https://github.com/BoostIO/Boostnote/pull/2209
