### ISSUE TITLE
<  > don't show at markdown preview.

### ISSUE THREAD

**Issue by kazup01** [BoostIO/Boostnote#205]
![jan-04-0029 23-47-31](https://cloud.githubusercontent.com/assets/8602615/21646346/25638562-d2d9-11e6-8d10-db7539dccac7.gif)

< and > are change to  , &gt; and &lt; at the markdown preview.

**Comment by asmsuechan** [comment]
This bug arises at  https://github.com/BoostIO/Boostnote/blob/master/browser/components/MarkdownPreview.js#L204

`markdown.render(value)` returns correct (like `<?php ?>`) value, however it is assigned to innerHTML as html comment `<!--?php ?-->`.

**Perhaps**, it occurs due to the settings of CodeMirror around auto completion.

**Comment by igoradamenko** [comment]
I think there is an appropriate issue.

If I use JSX in markdown block of code, I get something strange:

![gif](https://cloud.githubusercontent.com/assets/6537798/22907001/297532e2-f258-11e6-9418-6648a60e960a.gif)

Note: app version is 0.8.5.

**Comment by kazup01** [comment]
Hi @igoradamenko san, @asmsuechan fixed this bug.🎉
We will update next version! Thank you for waiting!
