### ISSUE TITLE
Delete Not Fast Enough

### ISSUE THREAD

**Issue by infosisio** [BoostIO/Boostnote#2156]
When you delete a note, the view area of the note is not cleared until you click on another note.
It would make the user experience feel much better if that was instant.

**Comment by ZeroX-DG** [comment]
@infosisio which version are you on? I deleted a note on the latest version (v0.11.7) and it immediately switch to the next note

**Comment by infosisio** [comment]
@ZeroX-DG That's the version I use on Ubuntu 18.04 and it doesn't switch to next note immediately here.

**Comment by ZeroX-DG** [comment]
@infosisio that's wierd, I'm using Linux Mint 18.2 and it work fine.
![peek 2018-07-03 18-47](https://user-images.githubusercontent.com/12984316/42218128-c477a92e-7ef1-11e8-9881-b2bf98dc33e3.gif)
Can you describe how can I reproduce the problem?

**Comment by infosisio** [comment]
@ZeroX-DG  I was not talking about the list change, I was talking about the fact that the screen is not cleared and it still shows the deleted note.

**Comment by infosisio** [comment]
@ZeroX-DG Will let you know soon.

**Comment by infosisio** [comment]
The fixes of max-buranbaev solved the issue.

**Comment by modmod24** [comment]
The same happens when you delete a tag inside your note. 
# Steps to replicate
1. click on tag in the list of tags -> all notes containing this tag will be shown
2. select one of this notes
3. delete the tag chosen in step 1 from the note chosen in step 2
4. observation: note disappears from list of notes but editor remains unchanged 
------
This is probably the same issue and already fixed by @ivanovserge and @max-buranbaev, I just wanted to mention it as another test case. 
-----
OS name, version: Ubuntu, 16.04.4
Version: v0.11.6
