### ISSUE TITLE
Note does not appear in the list if you created it from starred.

### ISSUE THREAD

**Issue by max-buranbaev** [BoostIO/Boostnote#2186]
# Current behavior
Should we have create a note button when click to starred? If you've opened stared notes and than created a note it won't appear in a list. 
![bug](https://user-images.githubusercontent.com/7540660/42340122-b27b917a-807e-11e8-9880-83685d636807.gif)

# Expected behavior
I think either we should create starred note or hide this button if starred is active. 
# Steps to reproduce

1. Open starred
2. Click create a new note
3. Note is not appeared in the list.

# Environment

- Version : 0.11.7
- OS Version and name : Mac OS 10.13.5

**Comment by modmod24** [comment]
I disagree. I think creating a new note should have consistent behaviour and you should be able to create a new note regardless of where you are (Notes, Starred, Trash).

**Comment by modmod24** [comment]
then again, there _is_ currently inconsistency, since you cannot create a note if you select "Trash". You are right your expected behavior would lead to consistency. I'd rather suggest, though, another solution:
# Expected behavior
- Don't hide the create note button, no matter if you are on Notes, Starred, Trash. 
- Creating a new note behaves always the same

**Comment by Flexo013** [comment]
The note does no longer disappear in the current version of Boostnote.
