### ISSUE TITLE
code preview error

### ISSUE THREAD

**Issue by lvshutao** [BoostIO/Boostnote#2217]
# Current behavior

1. code preview show error

<img width="628" alt="2018-07-19 21 34 09" src="https://user-images.githubusercontent.com/3890796/42945666-861cc658-8b9b-11e8-88f6-322a44bf3f72.png">

php `$` and single quotes error

2. in the editor mode, when tap one `*` at the begin of new line, it become to `**`

# Environment

- Version :0.11.8 (0.11.8)
- OS Version and name :10.13.6 (17G65)

**Comment by Rokt33r** [comment]
We still have a bug when sanitizing markdown. It is broken now. But, you can disable it!

<img width="1435" alt="screen shot 2018-07-20 at 0 15 31" src="https://user-images.githubusercontent.com/5865853/42951847-1b68cb9c-8bb2-11e8-9358-5a9c6c2d2422.png">

**Comment by Redsandro** [comment]
I installed latest Boostnote (because I reinstalled Linux) and now **all** my code snippets are broken with `&quote;`, `&apos;` (#2220) and other encodings or escapes (#2227). Snippets become hard to read. I cannot use the 'copy snippet' button, which I use daily, anymore. :angry: 

@Rokt33r You really can't release a feature that causes something to be so blatantly broken.

Ideally there will be tests that will check the parsed output. Using your favorite CI with a github hook, any PR would be verified against these tests, and if something breaks, _it can not be merged_.
