### ISSUE TITLE
Don't auto close asterisk (*) in markdown

### ISSUE THREAD

**Issue by nesmyslny** [BoostIO/Boostnote#2249]
# Current behavior

Since version 0.11.8 when typing an asterisk it gets closed automatically. So, this is the result of typing one asterisk: `*|*`.
I get that it makes sense for formatting text, but it's very annoying when working with lists. It's hard to estimate what people use more, in my case it's definitely lists ;)

It's also mentioned in #2243.

# Expected behavior

Typing an asterisk doesn't close it automatically.

# Steps to reproduce

1. Type `*`
2. Get `*|*`

# Environment

- Version : 0.11.8
- OS Version and name : Linux

**Comment by digitaljhelms** [comment]
In the primal editing environment Boostnote targets, it makes sense to me that `*|*` should only be applied when there is selected text.

**Comment by digitaljhelms** [comment]
Unfortunately it isn't subjective, https://daringfireball.net/projects/markdown/syntax#list stipulates `-`, `+`, and `*` can all create unordered lists...

**Comment by digital-carver** [comment]
The best option is of course to leave it to the user to decide, as a customization. I use lists a _lot_, and this behaviour is a big hindrance to productivity - enough to push me away from Boostnote a bit. I wouldn't even want it enabled when there's selected text or depending on what follows the `*` - principle of least surprise. Of course, others like @palermog might prefer that behaviour, which is why there should be an Editor option to customize it. 

The person who introduced Boostnote to me said it was "highly customizable", but at least when it comes to the Editor it's really not. There's no option to disable this auto-closing, none to disable the auto-placement of asterisk on the next line when the previous line has an asterisk (I often want to create sublists, and prefer using `-` or `+` for those, not `*`), the Editor section of the Interface preferences is in general very barebones. For a tool that has "customizable" in its tagline, it doesn't feel very customizable.

**Comment by ZeroX-DG** [comment]
You can now customize this by removing the ** from setting.
![image](https://user-images.githubusercontent.com/12984316/56135851-b1675700-5fe5-11e9-9bfc-b58869aebc6c.png)
