### ISSUE TITLE
No Markdown Preview only panel possibility

### ISSUE THREAD

**Issue by Shosta** [BoostIO/Boostnote#2266]
# Current behavior
In the main panel, you can edit and see a preview of the Markdown, you can just see the editing panel.
But you can't see only the result of the formatted Markdown

![boostnote](https://user-images.githubusercontent.com/1763733/43768656-1d94bcfc-9a38-11e8-9053-a6d43861bf93.png)

# Expected behavior
It would be good to have a button in the upper interface to just display the result of the Markdown.
Once I have edited properly my note using Markdown and I am coming back later to see the content of the note, I don't care in editing the Markdown but just seeing the result.
# Steps to reproduce

1. Open a markdown note
2. Try to display only the Markdown result in the panel (and not the editing Markdown and the preview)

# Environment

- Version : Boostnote 0.11.8
- OS Version and name : Ubuntu 18.04

**Comment by ehhc** [comment]
It is already possible.. just toggle the following button:
![grafik](https://user-images.githubusercontent.com/10086873/43820334-4286df28-9ae6-11e8-8120-a0dc201932cf.png)
and click somewhere else so that your not in the editing-option of the note (e.g. switch the program or open another note)

to edit your note you have to click on the markdown preview again -> it has the focus again and can be edited

**Comment by Shosta** [comment]
Yes but on Linux, it brings two panels (editing and preview).
And I would like to have only the preview.
As I read more documentation about the app, I saw that you can have it with typing the hotkey ctrl-W
So it works through a hotkey.

Thanks for your answer.

**Comment by alsora** [comment]
@Shosta It's working for me on Ubuntu 16.04.
The instruction si tricky, but after a while I got it.

The toggle switches between two modalities: shared screen and full screen. When you are in full screen, if you are visualizing the raw file you can pass to the preview by clicking everywhere outside of the editing window. Similarly, if you are visualizing the preview, you can click on it to pass to raw view.

**Comment by Shosta** [comment]
Yes, I can make it work as well. It is indeed not that clear for newcomers. But when you are used to it, it is very easy and useful.
I just have to click outside of the editing pane on full screen mode.

**Comment by gitname** [comment]
I haven't been able to get Boostnote to display the preview panel by itself.

With Boostnote 0.11.11 running in Windows 10, this is what happens when I click the toggle button when I am either focused on the editor window or focused on the preview window:

![2018-11-25_23-13-59](https://user-images.githubusercontent.com/7143133/48998343-0faf9e00-f108-11e8-8f82-5bea3b594965.gif)

In this example, I am in Boostnote's so-called "Fullscreen" mode, but the same thing happens when I am not in that mode.
