### ISSUE TITLE
Notes transfer to another machine

### ISSUE THREAD

**Issue by asmsuechan** [BoostIO/Boostnote#229]
Hi, once I moved notes to another machine. Then I had to take troublesome steps. Now it's still unmodified.  It's convenient for transfer that I can get a notes file on GUI and it can be imported on GUI.

**Comment by kazup01** [comment]
Hi @asmsuechan san, thank you for your everyday supports.
Boostnote can import existing files from storage setting (Menu -> Sotages -> Add storage -> Location).
But this is troublesome step, so I think we need to improve, too.

**Comment by asmsuechan** [comment]
I close this for now.

**Comment by LuSo58** [comment]
Hi, I have the latest version and it's not quite working. When I add the location it seems it does nothing. As I later figured out, it creates the link, but you have to restart the app to see the effect. The problem is, that it loads all folders correctly with 0 notes. I have tried this multiple times with the same result.

I am using Archlinux, with everything up to date, GNOME and my Boostnote package is from AUR (same version as latest release).
