### ISSUE TITLE
11.8 Using C# as a tag

### ISSUE THREAD

**Issue by zzxxhhzxh** [BoostIO/Boostnote#2321]
# Current behavior
When using "C#" as a tag, this tag can not be clicked to show the notes.
"C##", "C#a" also can not.

# Expected behavior

# Steps to reproduce

1. 
2. 
3. 

# Environment

- Version :
- OS Version and name :

**Comment by modmod24** [comment]
how were you even able to add `C#` tag? I wasn't. Same for `C##`, `C#a`

# Environment

-----

- Version : 0.11.9-pre.1
- OS Version and name : 16.04 Ubuntu

**Comment by zzxxhhzxh** [comment]
My version is 0.11.8, I use windows10 64 bit.
I can input C# just like you.


![image 001](https://user-images.githubusercontent.com/42593813/44469960-31bbf080-a5ee-11e8-8433-70aa0282f9db.jpg)

**Comment by modmod24** [comment]
# Current behavior

I upgraded to version 0.11.9-pre.2 and am now able to create the tags `C#`, `C##`, `C#a`. Tags are now clickable but it doesn't work right. 

# Steps to reproduce

1. create note, tag with `C`
2. create note, tag with `C#`
3. observe: both tags exist, each containing 1 note
4. click on tag `C#`, observe: notes tagged with `C` are listed, notes tagged with `C#` are not listed

@zzxxhhzxh is this what you where experiencing on your system? The behaviour is different to your description. 

![master_branch](https://user-images.githubusercontent.com/25648628/44981822-a2a6c500-af6b-11e8-937a-d182a8cfded9.gif)


# Expected behaviour - branch "fixing bug #2321"

![branch2321](https://user-images.githubusercontent.com/25648628/44981833-ac302d00-af6b-11e8-8a27-936ac840b7cf.gif)


tags should correlate with notes. I checked out branch from @daiyam and everything works as shown above. The .gif doesn't show it but `this/is/a/test` works as well. 

# Environment 

Version : 0.11.9-pre.2
Version and OS : 16.04 Ubuntu

**Comment by modmod24** [comment]
Update: I reverted to 0.11.8 the behaviour is the same as 0.11.9-pre.2
