### ISSUE TITLE
Shortcut to move cursor to beginning of a row does not function as expected. Shortcut to move to end of row does.

### ISSUE THREAD

**Issue by davidwolfpaw** [BoostIO/Boostnote#2427]
# Current behavior
_Note that I'm referring to a visible line of text in the editor as a "row" to differentiate from actual lines._

When you type a long sentence or paragraph, it will take up more than one  row in the Boostnote editor, while still occupying one line. The issue is that usng a shortcut like cmd + ← to jump to the beginning of the row instead jumps to the beginning of the line. 

Using a shortcut like cmd + → to jump to the end of the row works as expected however.

![sep-28-2018 09-05-13](https://user-images.githubusercontent.com/1971070/46210159-fb187a80-c2fd-11e8-9065-b15aad888d04.gif)

# Environment

- Version : Boostnote 0.11.9
- OS Version and name : MacOS v 10.13.6

**Comment by rscott** [comment]
I looked into this for fun. This is because this is the default behavior from CodeMirror (https://codemirror.net/doc/manual.html#commands). I'll submit a PR and the maintainers can decide if this is worth fixing. FWIW, Cmd+A goes to the start of the line and Cmd+E goes to the end, as you may expect.

**Comment by Flexo013** [comment]
This behavior seems to be solved in 0.14.0, at least on Windows 10 when using the Home and End keys.
