### ISSUE TITLE
How are notes synced between Desktop and Mobile?

### ISSUE THREAD

**Issue by raelb** [BoostIO/Boostnote#2521]
I could not find any information on the website (`https://boostnote.io`) how notes are synced between desktop and mobile.

Is there some information available on this?

Thanks

**Comment by modmod24** [comment]
hi @raelb, 

synchronization is currently not handled by Boostnote itself. You can define a storage location in boostnote and synchronize it via 3rd party application, i.e., Dropbox, Google Drive, etc.

**Comment by alickmail** [comment]
However the file type is something like this:
```
29621840-9ea1-45ac-bda8-043c006ca3ef.cson
```
May I ask how can I read these files from mobile? Many Thanks!

**Comment by nicklayb** [comment]
I have seen the post about syncing through google drive, but I think it would be way more efficient to use google drive api instead of folder. I do not have the google drive app installed and don't want to install it, it would have been simpler to setup an Google API token through the App.

Any plan on this?

**Comment by kyet** [comment]
refer to this,
https://github.com/BoostIO/boostnote-mobile
