### ISSUE TITLE
Shortcuts for moving folder

### ISSUE THREAD

**Issue by asmsuechan** [BoostIO/Boostnote#271]
Hi, I want shortcuts for moving folder like moving notes. I suggest `Ctrl + Shift + U` and `Ctrl + Shift + J`.

**Comment by justin-calleja** [comment]
@asmsuechan I assume you mean "navigating folders" by "moving folder". I have started implementing something. I don't know what's being used to track who's working on what. Just wanted to let you know so we can avoid doing the work twice (assuming you like what I'm implementing). So far:

 https://github.com/justin-calleja/Boostnote/commit/7fe7d37b5aed6519c56fae534b747a0b79ecc43f

There's up / down support (via arrow keys and Ctrl+n, Ctrl+p (emacs mode (by default work in terminal - since it's meant for developers these shortcuts are likely to be familiar - we can add others)). Also, there is visual indication when focus is lost (e.g. editing note). Clicking the SideNav will focus the active StorageItem (Storage / Folder). Perhaps there should be a shortcut to focus the NavBar from elsewhere... but that can be done later.

What I'd like to implement is right / left support. You should be able to navigate notes in a folder by hitting right arrow key, and collapse folders in a storage by hitting left (or go to storage if you're on a folder).

What do you think about this behaviour? I'll PR once I get it done all the way.

Cheers

**Comment by asmsuechan** [comment]
Hi, @justin-calleja! Thank you for your great work :+1:

> I don't know what's being used to track who's working on what.

Exactly. It's a problem. I'll manage to tell you what I do on a slack channel.

**Comment by justin-calleja** [comment]
@asmsuechan part 1 of what I had in mind for this is up here:

https://github.com/justin-calleja/Boostnote/commit/d618b3825933f2d85f1c7d7e5867eb79595d173c

I've started writing part 2 on this branch:

https://github.com/justin-calleja/Boostnote/tree/issue-271-part2

but I noticed the NoteList's NoteItems already have **some way** of moving around. This **way** (I haven't looked into it) is not how I'm doing it for the StorageItems / folders (which is via `onKeyDown` handler).

At this point, I'd like your feedback on what's been done so far and what you think is best to do re movement of NoteItems.

Currently, there's the following (btw, no unit testing - only tested on my notes).:

1. up / down on storage items and their folders work, including moving between storages and looping back to SideNavFilter items.
2. shift + left closes the current storage if you're on a storage item or a folder within the storage item
3. shift + right opens the current storage if you're on a storage
4. ctrl + shift + left closes all storages (even if you're on a SideNavFilter item)
5. ctrl + shift + right opens all storages (even if you're on a SideNavFilter item)
6. There is some visual indication when focus is gained an lost in the SideNav. When there is focus, you can use these keyboard shortcuts to navigate.

(there are some aliases to these keys: https://github.com/justin-calleja/Boostnote/commit/d618b3825933f2d85f1c7d7e5867eb79595d173c#diff-36238a14c2f1e9d973958637edaeecbfR120)

Re 6. I just chose a [colour](https://github.com/justin-calleja/Boostnote/commit/d618b3825933f2d85f1c7d7e5867eb79595d173c#diff-045e41ef76433f3fa043e1ed09e9be3cR29). Also, I've copy / pasted my way through applying this colour in the `.styl` files - perhaps there's a better way (my CSS is in need of work).

**TODO**: Right arrow should unfocus the SideNav and focus the NoteList's current active NoteItem, from which you should be able to navigate via up / down. Right from a NoteItem should unfocus the NoteList and focus the SideNav, again allowing keyboard navigation.

**Comment by justin-calleja** [comment]
Demo:

![issue-271](https://cloud.githubusercontent.com/assets/3186719/25613431/7556ea62-2f2e-11e7-83be-c03a83e0f134.gif)

**Comment by Flexo013** [comment]
If #711 gets reopened then this issue can be reopened too.
