### ISSUE TITLE
Why ":storage" is not allowed to copy/paste? (boostnote 0.11.11)

### ISSUE THREAD

**Issue by galian123** [BoostIO/Boostnote#2783]
# Current behavior

I paste a image into note. and there is `"![](:storage\246c4991-7b59-44ce-8ff4-955a0328e5ec\9c6ca173.png)"`

Then, I created new folder (e.g. `images`) under this folder "246c4991-7b59-44ce-8ff4-955a0328e5ec", which is under "attachments" folder of my storage.

I want to use relative path in boostnote, so I put some images into `attachments\246c4991-7b59-44ce-8ff4-955a0328e5ec\images`. But I can't copy/paste `![](:storage\246c4991-7b59-44ce-8ff4-955a0328e5ec\` in boostnote. If deleting `:`, then copy/paste is ok.

First question: Why ":storage" can not be copied/pasted?
Second: Why can't we create custom folder name instead of using this "246c4991-7b59-44ce-8ff4-955a0328e5ec" folder name?

Thanks a lot for your effort.

# Expected behavior

1.  ":storage" can be copied/pasted
2. we can create custom folder name instead of using this "246c4991-7b59-44ce-8ff4-955a0328e5ec" folder name.

# Steps to reproduce

1. paste a image into note. and there is `"![](:storage\246c4991-7b59-44ce-8ff4-955a0328e5ec\9c6ca173.png)"`
2.  I can't copy/paste `![](:storage\246c4991-7b59-44ce-8ff4-955a0328e5ec\` in boostnote. If deleting `:`, then copy/paste is ok.

# Environment

- Version : 0.11.11
- OS Version and name : Windows 7

**Comment by ZeroX-DG** [comment]
@ehhc Can you answer this question?

**Comment by ehhc** [comment]
The thing is, like it is implemented at the moment, the "246c4991-7b59-44ce-8ff4-955a0328e5ec" is the id (resp. "name") of your note. Attachments (not only images) are in a folder corresponding to the note they are referred in. There are several reasons for this: e.g. otherwise it would not be possible to automatically delete attachments that are not needed anymore (because they are not referrenced anymore).

I don't understand why you even want to use the same attachment in several notes instead of using the default mechanism and let boostnote handle it.. i mean: yes in that case there are multiple copies of the same attachment (-> more disc space needed) but all the thinks (like cloning notes, exporting them, etc) works.

Why don't you simple drag&drop the image into the new note? :)

**Comment by Diomas** [comment]
As to me this automatic deletion of unused attachments is quite annoying. At least in it's current implementation. Even if I copy/paste attachment references inside the same single note, I ended up with a deleted file sometimes. So to be safe i have to copy attached files somewhere outside boostnote storage, do bunch of edits to note then close boostnote app and copy missed attached files back to attachment folders.

I'll try to capture exact steps to reproduce and create bug for this.

Duplication of the same file if it's used in different notes is also strange

**Comment by Flexo013** [comment]
I don't see a reason to keep this question issue open anymore, mostly since it doesn't have any traction within the community. If anybody can think of specific improvement we could make to the app concerning this question then I will reopen this issue.
