### ISSUE TITLE
Nice with some wierdness

### ISSUE THREAD

**Issue by Cryo99** [BoostIO/Boostnote#2991]
# Nice but what...

All comments are based on:

BoostNote v0.11.15 
Windows 10

I'm hoping someone can help me understand BoostNote better. Like many others, I have been searching in vain for the perfect personal note manager/wiki with Markdown support, for years. There's a lot to like here, UI, themes, diagramme integrations, etc. but I am struggling to understand some things.

# Views

How do I view my notes without the editor?

The point of applications like this is to work with your notes. I can't find any way to hide the editor so I can do that. There is an editor view and an editor-with-preview view. which is great, but how do I just view my notes? This is so fundamental that it has to exist but where?

#### EDIT
I have just noticed that if I go into the prefs, for example, and then return to my notes, the selected note will be in edit mode however, if I then click off the note list in the blank space in the index below the titles, the view changes to a normal view i.e. not the editor. If I click around the titles again pages are loaded in edit mode and, sometimes but not always, they return to normal view when I click outside the list of titles. This is the only way I have been able to access a view without the editor.

There is definitely a bug here. I assume that it relates to the lock behaviour mentioned below.

# Controls

The view toggle isn't user-friendly and what does it actually mean? Am I in edit mode when I click on the pencil icon or what I think is supposed to be a preview icon? When I click on the preview icon the preview disappears. I see that the toggle switch hides it but that seems counter-intuitive. having to move the mouse to toggle left and right is also a pain. This seems like it should be clearer and easier to use.

# Lock what?

...and then there's the 'lock' (eye) icon. What is this supposed to be? It doesn't lock anything. I'm presuming it's intended to prevent editing but is broken... #1163, #1760, #1767, #2121, #2390. 
The icon itself is, again, unhelpful here. It implies you're disabling a view of some kind but it isn't intuitive and the tooltip fails to help. Is this how I am supposed to be able to view my notes without the editor? It's not documented anywhere, either even though the 'feature' appears to be two years or more old!

# Snippet notes
I don't get these. What are they supposed to be for i.e. what's the use case? I can do everything _except_ add tabs in a normal note. I must be missing something here but I can't see the point? The only insight I have is the new note dialogue which says that it can group multiple snippets into a single note, but that's possible by default. In addition, I _can't_ add text normally, due to the limited editing field at the top. I just don't understand. How are others using this?

# TeX
I tried the snippet offered here, just for fun:

https://github.com/BoostIO/Boostnote/wiki/TeX-support

It fails with:

> KaTeX parse error: $ within math mode

and prints the source minus the `$$` tags.

# Blog prefs
What is this? Again, no docs. Not useful.

# Snippet prefs
Likewise.

These aren't used when I create a snippet note and there's no option to choose them so....

# Hierarchy

Why you'd write an application like this without the ability to nest notes I can't imagine so I was happy to read that it is happening soon. I look forward to seeing that capability.

# Plug-ins
I searched around and read some things so I see that there is no plug-in system. I didn't find any reference to one being developed. I'm really that hoping someone is going to tell me that this is happening as a high priority because it's critical if you want this to grow. I'd be interested in contributing myself, if I could, as that would give me a means of obtaining the features I'd like to see.

# Crowdfunding
Finally, I have to mention this particularly badly chosen comment in the crowd-funding description:

> It sometimes looks like exploitation.

We contribute to FOSS software on the understanding that we do so voluntarily and freely. No-one forces us to do so. That's not exploitation, it's a choice. You are free to make your work commercial if that's your choice but please don't suggest that someone who uses software offered freely is exploiting others.

I hope the BoostNote team fixes the apparent bugs and continues to develop the tool because I think it has a lot of potential. The ability to contribute and extend the feature set would open up many options and the hierarchical note option seems essential. It may not be ready for prime time, yet, but I'd be happy to be proven wrong if others can help.

Cheers.

**Comment by ZeroX-DG** [comment]
The team is working on a re-write version of this app which promises to solve all these problems, but they have too much work to work on with other projects so the progress is slow. Right now, we have no choice because everything in the codebase is tied together now so it's hard to add more features. You can help us by submitting PR to fix the error that you stated above. Thanks for reporting all the main issues and sorry for this inconvenience.

**Comment by AWolf81** [comment]
Thanks for your feedback.

Plugins are discussed in issue #1018 and some other issues but no progress so far.
I like the idea and also think this should get a high prio - I will try to support here but I'm pretty new to BoostNote and that's a larger task that I'd like to delay a bit.

I think it's better to fix the smaller issues first I've also noticed some of your mentioned points like:
- Preview toggle button is not intentional & weird. It would be better if there would be more toggle states (fullscreen edit mode, side-by-side editing, view mode) and each click should toggle to the next state in a right to left order and back.
- Lock button seems broken & I'm not sure how this should work. Is this a write protection for a note? Or has it something todo with the viewing locked to view mode?
- Hierarchy feature is really missing and I think that's not that hard to implement with a library for the folder drag & drop menu (e.g. [react-sortable-tree](https://github.com/frontend-collective/react-sortable-tree) with a custom theme). I've worked a bit on this but nothing pushed yet - maybe one of my next features.

At the React upgrade to the latest version I've learnt a lot about the code base of BoostNote so I think I'm getting faster with adding / improving the app. But I still like to start with smaller things & do code base improvements first (e.g. Redux reducers in separate files, action creators etc).

Also I would do dev experience improvements first before adding new features as this is important for me & it will help new devs to get faster into the code base. A big improvement will be issue #1561.

**Comment by Flexo013** [comment]
The views and controls discussion is continued over here: #2196 

The lock button has since changed appearance. We could change the hover over text to say "Lock view mode" to be more explicit than just "Lock".

The TeX snippet provided should now work. Provided you have the same delimiters. (I added a mention of this on the page itself as well).

Improving of blog documentation is in the works: #2814

Snippet preferences is unclear to me as well, but then again I don't use snippet notes myself. Maybe we could add an info button :information_source: which could display some basic explanation about preferences section that could use extra explanation.

Hierarchy is being worked on actively now.

**Comment by Cryo99** [comment]
I'm going to close this. A lot of great work has happened since I wrote it and Boost Note is looking really good in the latest desktop version. I note that a UK English locale is still needed and that the plugin system is yet to appear but things are much, much better overall. Well done, that's great to see. I'm hoping to get my notes converted over soon and here is where the plugin capability would really shine. The tool I currently use doesn't provide a lot of export options and I see that I can only import markdown and text to Boost Note. I will have to use text and lose all formatting, unfortunately. The community would provide all sorts of import/output plugins if it could, I'm sure. I look forward to seeing that and being able to contribute. 😁 🤘
