### ISSUE TITLE
Too many warning signs in notes

### ISSUE THREAD

**Issue by zzxxhhzxh** [BoostIO/Boostnote#3035]
# Current behavior
Too many warning signs in notes. 
![warning signs](https://user-images.githubusercontent.com/42593813/58363837-0bbec780-7e70-11e9-912e-757e5e1b0a25.png)

# Expected behavior
There should be a option for show/hide warnings

# Steps to reproduce
Almost in everywhere.

# Environment
- Version : 0.11.16
- OS Version and name :  Windows 10 1903 insider preview

**Comment by vicgin** [comment]
I like the warnings and would also like to be able to turn them off with a preference... 
Being able to learn from them by having a code reference and explanations would be perfect.

**Comment by AWolf81** [comment]
PR #3034 will add the setting to enable linting and the default will be linting disabled.

But we'll discuss the default for linting in that PR. I think linting is a feature that not everybody will use, it's more for advanced users and a personal decision if you like linting or don't like it.

Adding a reference for the linting rules is a good idea. I'll prepare a docu section for it later today because there should be also an info on how to use the custom linting field in the preferences.

**Comment by 1300602123** [comment]
自动更新后就这样了

**Comment by AWolf81** [comment]
@1300602123 if google translated it correctly - yes, that's happening after automatic update because version 0.11.16 is enabling linting by default and there is no option to disable it at the moment.

@Rokt33r will release a new version soon that will improve the behavior.

**Comment by Flexo013** [comment]
0.11.17 has been released and allows for configuration of the Markdown lint. By default linting will be off, so the warning signs will disappear once you update.
