### ISSUE TITLE
Create user define-able markdown templates.

### ISSUE THREAD

**Issue by astrolope** [BoostIO/Boostnote#3087]
# Current behavior

I would like to be able to create custom templates other than the standard Markdown Note / Snippet note template. 

# Expected behavior

Allow users to define custom markdown templates that could be displayed within the compose widow.

# Steps to reproduce

1. 
2. 
3. 

# Environment

- Version :
- OS Version and name :

**Comment by Flexo013** [comment]
The reason for choosing between Markdown Note and Snippet Note is because they are fundamentally differently displayed. This does not pertain to any templates.

If you want to work with templates in Boostnote then maybe try the following:
1. Create a directory called 'Templates' in one of your storages.
2. Add markdown notes to this directory. Where each note will be a different template.
3. Whenever you want to create a new note using a template, simply right-click the correct template, and select 'Clone Note'.
4. Move the new note from the Templates directory to whatever directory you want it.

You can already easily use templates in this way, without Boostnote needing new functionality.

I don't think adding different buttons for template to the create note menu is a good idea.

**Comment by ZeroX-DG** [comment]
You can create a custom snippet in the setting and use it as a template
