### ISSUE TITLE
Boostnote doesn't start after update (0.11.15 old, 0.11.17 new)

### ISSUE THREAD

**Issue by Dene33** [BoostIO/Boostnote#3098]
# Current behavior

Boostnote doesn't start after clicking Boostnote.exe

# Environment

- Version : 0.11.17
- OS Version and name : Windows 10

**Comment by AWolf81** [comment]
Thanks for reporting the issue.

Are you getting any error messages?
Have you updated with the auto-updater or manually installed the new version?

I couldn't reproduce the issue yet. Maybe I'll test again with the auto-updater because I manually installed 0.11.15 and then 0.11.17 with-out any starting issues.

**Comment by ZeroX-DG** [comment]
I gonna need more information than that, can you provide any error that appears when you run the app?

**Comment by Dene33** [comment]
There are no errors. Boostnote just doesn't start. That happened after auto-update. Actually I'm not sure if that was `0.11.15` version that I had previously. But now I have `0.11.15` folder and `0.11.17` folder. `.exe` from `0.11.15` folder works, from `0.11.17` doesn't.

**Comment by ZeroX-DG** [comment]
Have you try to run the `.exe` from command line? It should log error to the command line.

**Comment by Dene33** [comment]
#
# Fatal error in , line 0
# Check failed: (isolate->snapshot_blob()) == nullptr.
#
#
#
#FailureMessage Object: 00000033701EEB40

**Comment by AlexMV12** [comment]
I don't know if it is related, but tonight, after an Electron update, Boostnote is not starting anymore (the loading icon keeps rotating).
After downgrading Electron, the problem is gone.

Screenshot:
![immagine](https://user-images.githubusercontent.com/36054651/60402168-495bf200-9b8c-11e9-8cf8-793aa9b5b9cc.png)

App version: 0.11.16-1
OS: Arch Linux

Boostnote IS WORKING with Electron 4.1.4
Boostnote IS NOT WORKING with Electron 5+.

If it is unrelated to this issue, I may open another one.
Feel free to ask for more information.

**Comment by ZeroX-DG** [comment]
@AlexMV12 I don't think your issue is related, please open another issue for it.

**Comment by ZeroX-DG** [comment]
@Dene33 it looks like your issue is similar to this: https://github.com/Microsoft/vscode/issues/70895

The way to solve it is to re-install the app.
