### ISSUE TITLE
about Zooming UI

### ISSUE THREAD

**Issue by Rokt33r** [BoostIO/Boostnote#31]
Putting Zoom select on status bar of GitKraken is quite brilliant design. It can be found easily while not annoying.
I'll try to imitate this feature.
![screen shot 2016-05-11 at 8 01 22](https://cloud.githubusercontent.com/assets/5865853/15165156/9d0d9cf2-174e-11e6-9952-c2daccf4f4ad.png)

**Comment by Rokt33r** [comment]
This feature will be shipped. Check #3

**Comment by whizark** [comment]
This is a really nice feature that many other Electron apps don't have :smiley::+1:
It would be nice if I could select more zoom % because the max zoom % was a bit small on large screen (3840 x 2160 etc.).

e.g. 130% (current max zoom, a bit small), 150% (readable), 175% (comfortable), 200% (super readable)
