### ISSUE TITLE
Couldn't install Boostnote - Squirrel Problems...

### ISSUE THREAD

**Issue by Zorono** [BoostIO/Boostnote#3302]
Hello everyone,
so when i was installing the awesome `Boostnote` in my x32-bit Windows device, i had the following error logs and the installer stopped suddenly.
[SquirrelSetup.log](https://github.com/BoostIO/Boostnote/files/3756402/SquirrelSetup.log)
please some help

**Comment by Flexo013** [comment]
It seems that Boostnote is unable to write to your local appdata folder. ([As suggested by this thread](https://github.com/Squirrel/Squirrel.Windows/issues/698))

Boostnote needs to write files to the local appdata folder, so that's why it is failing.

Are you an administrator on the device you are trying to install Boostnote on? If so, could you try running the installer as administrator?

**Comment by Zorono** [comment]
[SquirrelSetup.log](https://github.com/BoostIO/Boostnote/files/3756623/SquirrelSetup.log)

unfortunately, i tried running it as administrator but nothing different...

**Comment by Flexo013** [comment]
Another suggestion from that same thread is to try installing with your antivirus temporarily disabled.

**Comment by Zorono** [comment]
[SquirrelSetup.log](https://github.com/BoostIO/Boostnote/files/3816346/SquirrelSetup.log)
after upgrading to Windows 8.1 N Pro x32-bit,
it conflicts with DiscordCanary.exe(https://canary.discordapp.com)'s Squirrel(if iamn't wrong)

**Comment by Flexo013** [comment]
Could you try uninstalling DiscordCanary and then install Boostnote?

**Comment by Flexo013** [comment]
Closed due to inactivity.
