### ISSUE TITLE
Can't Install - Linux / .deb link leads to 404

### ISSUE THREAD

**Issue by chris-jansson** [BoostIO/Boostnote#3303]
# Current behavior

I get a 404 when following the download link on the Boostnote website.

# Expected behavior

The download link should download a .deb file for me to install.

# Steps to reproduce

1. Go to https://boostnote.io/
2. Click on the green download button
3. Submit email address
4. Click on LINUX / .DEB, 64BIT button
5. 404 happens

# Environment

Ubuntu 18.04.3 LTS

**Comment by oneryx** [comment]
The link is wrong, instead of
https://github.com/BoostIO/boost-releases/releases/download/v0.13.0/boostnote_0.12.1_amd64.deb

it should be
https://github.com/BoostIO/boost-releases/releases/download/v0.13.0/boostnote_0.13.0_amd64.deb

I build it from source and it shows version 3.0.8 (same as Electron) which is a bit of confusing.

**Comment by Flexo013** [comment]
I have pinged the people who can modify this. Hopefully it'll be fixed soon.

Here's an alternative download link that will always get you to the latest version: https://github.com/BoostIO/boost-releases/releases/latest

**Comment by chris-jansson** [comment]
Great, thanks for the updated links.

Just tried downloading from the website again, and now it works.

**Comment by Rokt33r** [comment]
Thanks for the reporting!
