### ISSUE TITLE
In text input mode, the shortcut key (Ctrl + [ & Ctrl + ]) does not work

### ISSUE THREAD

**Issue by gmqi** [BoostIO/Boostnote#3331]
# Current behavior
In text input mode, the shortcut key (Ctrl + [ & Ctrl + ]) does not work.
1. When I pushed Ctrl + [, there is no response.
2. When I pushed Ctrl + ], a tab was inserted.

# Expected behavior

1. When I push Ctrl + [, previous note is shown.
2. When I push Ctrl + ], next note is shown.

# Steps to reproduce

1. In the text input mode, input some character.
2. Push Ctrl + [ or Ctrl + ]

# Environment

- Version : 0.13.0
- OS Version and name : Windows_NT x64 10.0.18362

**Comment by Flexo013** [comment]
I understand the confusion, but this is intentional behavior. The problem is caused by conflicting hotkeys. Within the editor you use this key combo to increase or decrease the indentation of a line, which is very useful in lists. When you aren't in the editor the note switching functionality takes over those same hotkeys.

Currently neither of these hotkeys is configurable (which would allow one to change this conflict). #2645 is this issue for adding more configurable hotkeys.
