### ISSUE TITLE
Is There any way to import vim editor shortcut config like vimrc?

### ISSUE THREAD

**Issue by fnsne** [BoostIO/Boostnote#3360]
I just know that I can change the vim shortcut from [Here](https://github.com/BoostIO/Boostnote/wiki/Vim-mode#custom-keymaps)

But if I need to set a lot of shortcuts, I have to retype all custom shortcuts every time after restarting the Boostnote.

Is there a way to import a config file of vim shortcuts that I can easily load all custom shortcuts.
Or a way to set shortcuts that will be memoried. (after restarting the shortcuts are still set)

Thanks.

**Comment by Flexo013** [comment]
I'm not aware of any ways that you can store these changes, and the method that you link to seems like a work-around until this is properly implemented.

Could you try writing down all the changes once, saving that somewhere (maybe as a note) and then just paste the whole thing into the console? That should at least make the work-around a bit faster to use.

**Comment by fnsne** [comment]
@Flexo013 Oh, Thanks.
I never come up with this way.

**Comment by arcturus140** [comment]
you can place it in a script, wrap it around boostnote and use it as a launcher

**Comment by fnsne** [comment]
@arcturus140  
It sounds great. 
But I don't know how to give the setting through the command line. 
Could you describe more details about how to do that?
Thank you.

**Comment by RyanGreenup** [comment]
You can also just edit the files directly in vim it's only a text file, just bear in mind, because it is a `.cson` you will need to escape `\` characters, I just use something like `map <leacer>c :s/\\/\\\\/g` to highlight and then clean up everything after the fact.

A trick to speed this up is to copy a string of unique note text and then run the following in the terminal:

```bash
vim $(ag -l $(xclip -o -selection clipboard))
```
Then you should be able to wrap that in a bash script and assign it to a keyboard shortcut.

you could also use the note name from the information panel, but that involves taking your hands off the keyboard.

The biggest advantage to actually using vim directly is being able to use UltiSnips and other plugins, It's the same in RStudio/VsCode/Atom, as nice as better vim implementation would be, it's just easier to edit the file directly in vim.

**Comment by Flexo013** [comment]
@fnsne Is there anything else you need for this issue, or can we close this?
