### ISSUE TITLE
How to delete TAG?

### ISSUE THREAD

**Issue by aptxna** [BoostIO/Boostnote#3670]
Hi there! I accidentally created a TAG, and failed to delete it. How can I delete the tags?

**Comment by Komediruzecki** [comment]
> Hi there! I accidentally created a TAG, and failed to delete it. How can I delete the tags?

Hi, currently the right click on tag in tag list is not working since the context menu immediatelly closes. This will be fixed soon in a new update. Hence you will be able to right click a tag in "tags" list and click on remove to remove it from the storage.

For removing the tag from a note, just click the "x" button in the top view list of all note tags.

**Comment by aptxna** [comment]
> > Hi there! I accidentally created a TAG, and failed to delete it. How can I delete the tags?
> 
> Hi, currently the right click on tag in tag list is not working since the context menu immediatelly closes. This will be fixed soon in a new update. Hence you will be able to right click a tag in "tags" list and click on remove to remove it from the storage.
> 
> For removing the tag from a note, just click the "x" button in the top view list of all note tags.

Thanks! Looking forward to the new update!
