### ISSUE TITLE
[Discussion] About necessity of tag feature

### ISSUE THREAD

**Issue by kazup01** [BoostIO/Boostnote#371]
Hi there,
I have never thought that tag management as useful, and I have not using it.
There are many people around me who do not use it.

If there is anyone who uses the tag feature everyday, would you tell me how you use it?👀
If there are many feedback that tag feature is unnecessary, we will delete it to make Boostnote simple.

I'm glad even if you guys tell me via Reaction alone🙌

**Comment by burakcan** [comment]
I don't use tags in boostnote but actively using them in other apps. At their current stage in boostnote, they are a bit useless. But if there were filtering by tags; they might be useful as 
subcategories. Example: ( - = category, [] = tag )

- UI Notes
   [dashboard] [user profile]
- Development notes
   [dashboard] [user profile]

So if i'm working on dashboard, i could just filter to see [dashboard] tag and see both my ui and development notes.

**Comment by kazup01** [comment]
> At their current stage in boostnote, they are a bit useless

I agree.
Your use case is very helpful. Thank you for your info @burakcan san!
What do you think about switching  Folder and Tag area in sidebar like below image?
<img width="405" alt="59ca3e98-02bf-11e7-8585-120af483643f" src="https://cloud.githubusercontent.com/assets/8602615/24548025/e8011406-164d-11e7-9038-745f3fa24128.png">

**Comment by kazup01** [comment]
I'm glad even if you guys tell me via Reaction alone🙌

**Comment by burakcan** [comment]
@kazup01 that could be very useful <3

**Comment by VoLuong** [comment]
**Do I use them on a daily basis?**

No, I dont use Boostnote everyday.

**Do I extensively use tags?**

Yes, in every note.

**Why? What is my use case?**

Because tags are extremly useful and of top importance.

1. To keep things organize
2. To quickly find things without remembering where they are
3. To mark some highlight features of the notes.

`example:` I noted down a bunch of sorting algorithm in a `Sort Algo` notebooks. When I need to find one that I suddenly need, what do I do ? Why should I rummage through my notes instead of typing down something inside the search box? Do I need some algorithm easy to remember? Go search `easy-to-remember` and bubble sort pops out with the tag that I previously assign to it. Do I need the fastest algorithm? Go search `fastest` and even while I was just typing `fas` quick sort pops out. That's how easy it is. 
Moreover, you can dramatically reduce the notebooks you have to create by using tags. Let's say I came accross a jquery code one day and I want to keep using it because it brings a nice transition effect. Do I need to create a notebook `Jquery` then create a note `nice effect` in it? Why would I need to do so when I can just place it in my `random nice things` notebooks with tags like `jquery`, `nice effects` ?

4. More seriously, I can put priority tags to my notes.

I usually have a notebooks consisting of all my todo lists and tasks of the day. (although I haven't tried this with Boostnote, anyway). Having tags around help me see which things I need to focus on depending on their importance. For example, first thing I need to do tonight is to take my mother out for a ramen, then okonomiyaki. With tags, I can easily assign `1st`, `2nd` without worrying which one should I eat first.

**Comment by jasondavis** [comment]
I am a huge Tag user in general.   As mentioned not so much in Boostnote since they don't work to show records matching a selected tag.

The reason I love and use tags in addition to Folders and categories is the sole reason that a single record can be tagged with multiple tags wgere it can only be in 1 category/folder.

---

## Example

If I have a record that stores a JS library code, some documentation, and example usage of the library.  I might store that in a Collection named **Code** that has a sub-folder named **JS-Libraries**

Now that works great, if I need to find that record it is pretty easy to find in my code library under JS-LIbrary folder.  However now if I have 3-4 records for other projects and they need to use that library orr acess it, with the use of Tags I would be able to tag the record to show up when I view any of those libraries.

This probably isn't the best example.  Where I really use tags a lot is in my massive organized Pinboard Bookmarks collection.  Each bookmark is Tagged with many tags related to the bookmark.  A DateTime Picker JS library might get tagged with `JavaScript`, `DateTime-Pickers`, `Dates`, `Web-Dev`,`Time`, `Picker-Selectors`

Really I feel tags come into true value as your library grows to a large scale and you spend the time to properly tag items you can really get a lot of usage out of them.

**Comment by jasondavis** [comment]
Also the idea of using this UI in the sidebar to toggle view of folders and tags would be really slick and a nice UI and UX for the app!

![](https://cloud.githubusercontent.com/assets/8602615/24548025/e8011406-164d-11e7-9038-745f3fa24128.png)

**Comment by GaryFurash** [comment]
I really agree with everything above.

**Comment by kazup01** [comment]
Hi guys, thank you for you guys great feedback!👏 I created the new issue about tag feature improvement. Please check it! #519
