### ISSUE TITLE
Cannot delete, copy or cut selected text in editor window

### ISSUE THREAD

**Issue by johnnyleitrim** [BoostIO/Boostnote#3717]
# Current behavior

~~If I select text in the editor window, I cannot delete it; copy it or cut it. Pressing any of the delete keys does nothing. Using Cmd-C or Cmd-X (I'm on MacOS) does nothing.~~

This only happens if I use Shift-Cmd-Arrow to select an entire line - if I use any other way to select text, it works as expected.

<img width="1199" alt="Selecting Text" src="https://user-images.githubusercontent.com/4570406/126792179-3de90909-0423-4821-92f4-d837c5b5208e.png">

# Expected behavior

I expect to be able to delete, copy or cut highlighted text in the editor window.

# Steps to reproduce

1. Select a section of text in the editor window
2. Press the delete/backspace button
3. The text should be deleted, but isn't

# Environment

- Boostnote version: 0.19.0
- OS version and name: MacOS 11.4 (Big Sur)

**Comment by Komediruzecki** [comment]
Hi, johnnyleitrim,

You posted the issue in boost note legacy repository, and this is clearly boost note next.

For the issue, there was a bug going left/right to select things in editor in v0.19.0. 
The bug is fixed, so please update the application to latest version and let me know if you encounter any problems there.

**Comment by Komediruzecki** [comment]
This is resolved and fixed, if you encounter any more issues please create another issue.
