### ISSUE TITLE
Feature Request: Emoji Library

### ISSUE THREAD

**Issue by codingmatty** [BoostIO/Boostnote#373]
In the spirit of markdown and personalization, it would be awesome if Boostnote shipped with a small emoji library that could also be customized with the end result being `:wink:` => 😉

**Comment by kazup01** [comment]
Since priority of this issue is low, we will check it if you send us PR, is it possible?

**Comment by yesroh** [comment]
I can do this!

**Comment by kazup01** [comment]
Wow, great! @yesroh

**Comment by apiraino** [comment]
I'll chime in with a tiny request: please consider allowing Emojis to be completely disabled (like the Slack client does), in order not to burden startup time with lots of PNGs.

**Comment by asmsuechan** [comment]
@codingmatty Thank you for your opinion :smile: We need to consider it before we try to implement our own emojis. But Boostnote works at completely local. So I assume It's never very slow even if there are a lot of PNG emojis in a note.

**Comment by codingmatty** [comment]
So.. After perusing the codebase a tiny bit, I realized you already have an emoji library built in via [markdown-it-emoji](https://github.com/markdown-it/markdown-it-emoji).
It would be great to have support for autocomplete/search emoji library and being able to add custom emojis, but those are just nice-to-haves, and certainly not requirements..

**Comment by xpac1985** [comment]
@codingmatty I might overlook something - but is it already possible to use that built-in emoji support? Simple emojis aren't converted for me, and I couldn't find any other documentation about it. Any advice would be appreaciated :-)

**Comment by modmod24** [comment]
I think this is a more useful cheat sheet: https://gist.github.com/rxaviers/7360908#file-gistfile1-md. 
Boostnote icon set is  black & white, can I replace it with my own?

**Comment by Shosta** [comment]
This issue was closed a few times ago but I can't see the result of it in the app.
I would love as well to have some kind of emoji autocompletion while I don't know the emoji name by heart.
Something like that extension in VSCode : [](https://marketplace.visualstudio.com/items?itemName=bierner.emojisense)
I don't know if it is that hard to do has you already have the [markdown-it-emoji](https://github.com/markdown-it/markdown-it-emoji) library? But I would love to have that feature in Boostnote.
