### ISSUE TITLE
Storage Created on ubuntu doesn't mount

### ISSUE THREAD

**Issue by NourEldin275** [BoostIO/Boostnote#454]
I was using it fine just yesterday and I had two storage options created. One on a WD mycloud drive (mapped network drive) and another one in home ~/Documents directory when I started the notes today (not connected to the mycloud network drive) it didn't recognize the local storage I created in the Documents directory. 

Now when I create new storage, it is saved in the settings menu but not available to be used and keeps saying no storage mounted.

**Comment by k4ch0** [comment]
Same here!
Boostnote version: 0.8.7
OS: Linux Mint 18.1

**Comment by frayedknot** [comment]
I am also having this problem OSX 10.12.6. with Boostnote v0.8.14. This occurred to me after a reinstallation of Boostnote. 

Is there a directory that needs to be blown away to ensure a "fresh" re-install?

**Comment by fsabado** [comment]
I ran into this issue recently. I had to remap a network drive that contains my notes. Seems changing the path causes issue when reloading the storage again. It might be related to this issue here: https://github.com/BoostIO/Boostnote/issues/1934. He had to change the drive letter of his storage in  the sqlite file/db in `C:\Users\my_username\AppData\Roaming\Boostnote\Local Storage\file__0.localstorage`.

I'm using Windows 10. But here is how I was able to do a "fresh" re-install in case someone else runs into this issue on Windows 10.

* Use Windows 10 uninstall normally.
* Delete `C:\Users\<username>\AppData\Roaming\Boostnote`
* Delete `C:\Users\<username>\AppData\Local\boost`

**Comment by Flexo013** [comment]
Feel free to comment here or reopen this issue if this is still occurring with the latest version of Boostnote.
