### ISSUE TITLE
[Discussion] About improvement of tag feature.

### ISSUE THREAD

**Issue by kazup01** [BoostIO/Boostnote#519]
refer to #192 #328 #371 #390 #503, thanks for @huettenhain @jasondavis and @kazuhisya!

I think should improve tagarea UX more, especially I want to improve the following two features. Please tell us you guys feedback!

## 1, Add tagarea at sidebar
<img width="557" alt="screen shot 0029-04-28 at 1 32 57 pm" src="https://cloud.githubusercontent.com/assets/8602615/25514739/eac9a28e-2c19-11e7-84a7-0a322d641f3d.png">

---

## 2, Can make tags inside markdown note and snippet title.
And will delete the tagarea at the top of NoteDetail.
<img width="653" alt="screen shot 0029-04-28 at 1 32 01 pm" src="https://cloud.githubusercontent.com/assets/8602615/25514744/f04969e2-2c19-11e7-8457-dc6f0df1dc65.png">

**Comment by huettenhain** [comment]
This looks pretty cool. I like the simplicity of it, allows for storing the tags inside the note.

**Question:** If I want just a list of tags that is not displayed in the note, would this work?
```
# My Cookie Recipe
<!-- #sugar #recipes #cookie -->

Ingredients:
 ....
```

**Comment by kazuhisya** [comment]
It sounds lovely!

But, about the second proposal(2, Can make tags inside markdown note and snippet title.), I can't image the behavior yet.
For example, in the case of Markdown notes, how does it behave?

**Comment by justin-calleja** [comment]
@kazup01

Re 2, are you planning on extending markdown to do this? Also, if you're removing the tagarea at the top of NoteDetail, how can one quickly see at a glance the tags associated with a note? Would you have to skim the note?

Personally, skimming the note would be less convenient. I'd rather have the current tagarea at the top of the note to create / remove and quickly see which tags are associated with the note.

Also, adding tags to notes in markdown... since this is something that native markdown does not support, I think it would make more sense to have this as a separate note type. There should be some separation between notes written in markdown and are compatible with other markdown supporting software, and custom stuff.

Personally, Boostnote should only have plain markdown note types out of the box. All other types could be plugins the user can install if relevant to them (to my mind, this includes the existing Snippet Note type - markdown can have code snippets after all).

In any case - totally agree with keeping simplicity as a priority OOTB, but if Boostnote is going to be interesting, it needs to support plugins. Currently, by "plugins" I'm thinking "supporting different note types". When I stop to think about it, there is potential for more if one is willing to bastardise one's Boostnote :)

For e.g. I've been meaning to write some kind of drilling software (to memorise things). I wanted to do this with the combination of tech Boostnote is using (Electron, React, Redux) - as practice. I came across Boostnote a couple of days ago while I was researching how to work with Electron.

What I'm trying to say is that, note taking is cool.. but the first thing that came to my mind was "I can use this as the base for my drilling app" (apart from a lot of infrastructure already being there - drilling and note taking seem to have some relation..  but true, Boostnote having drilling support OOTB would be bloating it).

Only problem, there is no plugin system.

I'm diverging here... to summarise:

1. Removing the tagarea might not be such a good idea unless there's some other (easy) way to see all tags associated with a note.
2. If you're going to extend markdown, please do it as a separate editor type.
3. Ideally introduce new editor types via some kind of plugin system and keep Boostnote simple OOTB.
4. If there's going to be a plugin system, can it be made generic? e.g. the use case above (embedded drill app) cannot be implemented if plugins are restricted to being only "different note types".

- - -

Re 1, seems like a great addition :)

**Comment by brpaz** [comment]
For the first one, yes I really missing that feature.

About nº 2, I would prefer to have as it is and not mixing tags with Markdown content.

**Comment by kazup01** [comment]
Thank you for you guys great feedback!
**"1, Add tagarea at sidebar"** sounds good. We will add it!

**"2, Can make tags inside markdown note and snippet title"** It seems necessary to considering.
As you guys say, it seems better to separate tagarea from markdown editor.

As an improvement idea, how about the following image? refs:#430
It is looks great to me because keep simple to Boostnote's UI.
<img width="770" alt="screen shot 0029-05-03 at 11 37 39 am" src="https://cloud.githubusercontent.com/assets/8602615/25646589/f16ce324-2ff4-11e7-88b5-772f4290e5b0.png">

**Comment by Airgunster** [comment]
Anyone knows when new tagarea at sidebar going to be available for tests?
*/would love to test it/*

Thanks a lot for that powerful and lovely software!

**Comment by chrishodgson** [comment]
I would also like to know about this tag filtering feature as am evaluating boostnote against quiver and medley. Quiver has tag filtering, medley doesn't but has a nicer UI. So currently its 1. quiver 2. medley 3. boostnote. If you could filter by tags it would be 1. boostnote 2. quiver 3. medley. I can't understand why you would bother to implement tags *without* the ability to filter them

**Comment by kazup01** [comment]
Hi guys, @sosukesuzuki is implementing the [Tag Filtering Feature](https://github.com/BoostIO/Boostnote/pull/922) like below image.
We will update it at Next Saturday.
![tag-area-image](https://user-images.githubusercontent.com/8602615/31044573-e425f4f6-a60c-11e7-9880-80df035b7f3a.png)

**Comment by kazup01** [comment]
Sorry for the late supporting. 
This feature will be released in this week!
https://github.com/BoostIO/Boostnote/pulls?q=is%3Apr+is%3Aclosed+label%3A%22Next+Release%22

**Comment by kazup01** [comment]
Thanks for you guys feedback!
