### ISSUE TITLE
Show first line of note in filename

### ISSUE THREAD

**Issue by Alexey-T** [BoostIO/Boostnote#532]
Will be good, if filename (hash) shows 1st non-empty line (e.g. limited by 30 chars)
in the filename after hash.
E.g.
`nnnnnnnnnnnnnnnnnnnnnnnnn[Some line from note here].json`

**Comment by Alexey-T** [comment]
(maybe not one line, e.g. "Hello", but many chars from text, e.g. 30 chars)

**Comment by Alexey-T** [comment]
@kvichans Consider this app, good app for saving notes.

**Comment by huettenhain** [comment]
Sounds like it will introduce a ton of problems and possible bugs / security risks. I do not see the benefit.

**Comment by Alexey-T** [comment]
Benefit: easy to find file by hands

**Comment by asmsuechan** [comment]
Hi, @huettenhain and @Alexey-T! I totally agree with both opinions. First of all, I don't contemplate to change the filename. But you know, it's hard to find a specific file by hand. And probably a note hash in [this PR](https://github.com/BoostIO/Boostnote/pull/336) helps us to solve this problem. Because the hash of filename is contained into the hash. I'm happy if you'd tell me what you think about my opinion :smile:
