### ISSUE TITLE
Shift / ctrl key introducing asterisks

### ISSUE THREAD

**Issue by justin-calleja** [BoostIO/Boostnote#540]
I hope this can be re-produced on your end.

When using markdown editor, try typing:

"hello:"

then pressing "ctrl+n" (for e.g. ) or just ctrl... in my case I get asterisks inserted (not always)... I use (ctrl + n, ctrl + p, ctrl + a, ctrl + e) from muscle memory to go to the next line, go to the previous line, go to the beginning of a line, and go to the end of a line.

![asterisks-issue](https://cloud.githubusercontent.com/assets/3186719/25613177/a479865c-2f2d-11e7-960d-602898ecff19.gif)

**Comment by sferra** [comment]
I also encountered this issue, which is *extremely* annoying. I usually trigger it when pasting text into notes.

It occurs at some point while editing notes, and seems to be triggered by first typing ':' and then pressing the control key. After it is first triggered, each press of the control key triggers the 'bold syntax' around text near the cursor. Moving the input focus away from the editor makes the editor behave normally next time it used.

**Comment by sferra** [comment]
@justin-calleja could you please check if you can trigger the issue the way i can? If this is the case then please update the issue title to reflect that the *control* key triggers the bug, and not the *shift* key.

**Comment by LeoLamCY** [comment]
How to replicate this:
hold down shift + ; and then release shift before releasing ';' then try hitting ctrl. You will get asterisks. (ctrl + :) is the shortcut for surrounding words with asterisks (bolding).

This happens because of how Boostnote detect multiple keys. When you hold down shift + ";", shift and ":" are registered as being "down" but then if you release shift first before releasing ';', then Boostnote will only detect that the shift key and the ';' key are released (instead of ':', because ':' is shift + ';'), but internally the ':' key is still registered as being held down even though it has already been released. So if  you hit ctrl after, you get asterisks, which is ctrl + ':'

This is a tough one to explain but here's the internal key states when the bug occurs:

- hold down shift + ;
keys that are down: {Shift: true, :: true}

- release shift:
keys that are down: {Shift: false, :: true}

- release ; :
(by now both keys are up)
keys that are down: {Shift: false, :: true} (because the ';' key is detected as released NOT the ':' key)

-hit ctrl now:
keys that are down: {Shift: false, :: true, ctrl: true} 
Hence you get asterisks.

I'll look for a way to fix it in the mean time.

**Comment by justin-calleja** [comment]
@sferra , you're right I meant ctrl key when I first opened the issue - my bad. Kept shift in the title because of @LeoLamCY 's findings.

@LeoLamCY I was able to re-produce:

> hold down shift + ; and then release shift before releasing ; then try hitting ctrl

Thanks, I'm looking at #545
