### ISSUE TITLE
Import/export to/from txt

### ISSUE THREAD

**Issue by rhoconlinux** [BoostIO/Boostnote#546]
Using Boostnote I found the lack of a function that I find very useful: the ability to import/import bunch of text files (or, at least, one) from notes. 

In this sense, It would be useful to be able to import flat notes from other programs. 
Also to allow to export notes from the xml. 

Probably this might help to parse the xml notes into txt notes: 
https://github.com/rhoconlinux/gnote-massive-export-to-txt

I hope this function can be implemented in the future! 

Thanks!

**Comment by sferra** [comment]
I'm not sure that I understand the problem. You could just paste the text from the plain text file into the note editor to "import" and the other way around to "export". The note contents are plain text and there is no XML involved.

**Comment by GaryFurash** [comment]
I'm confused, isn't there something someone already programmed to import a mass of text files into Boostnote - it just isn't in the current release. If I'm wrong I definately need this because sferra i don't want to spend a week cutting and pasting tons of files.

**Comment by sferra** [comment]
@GaryFurash *mass* import is something a bit different from the current issue description. For such a case, an import function definitely makes sense. :)

I wanted to clarify potential confusion about XML being used for storing the notes.

One of the features I personally would like to see implemented is the separation of the note metadata (date, tags, ...) and the note content. That way one could synchronize the notes more easily with other devices and edit the plain markdown files. If such a separation of content and metadata would be implemented, then an import function would just need to generate the required metadata for the files to import (and maybe only reference to the original files instead of copying their content).

**Comment by GaryFurash** [comment]
oh, cool. I need to import a bunch of text files. Did that ever get done? Where is it? Can I try it?

**Comment by sferra** [comment]
There isn't such functionality yet in Boostnote. Someone will have to implement it.

**Comment by GaryFurash** [comment]
What about https://github.com/BoostIO/Boostnote/pull/325. Didn't that guy do it?

**Comment by asmsuechan** [comment]
Hi, you guys! It's a PR to import 1 file (.txt/.md). And there's a feature to export 1 file (.txt/.md). Yeah, I'm going to implement *bulk* importer/exporter.

**Comment by rhoconlinux** [comment]
Cool @asmsuechan !
Thanks for the effort!
:dancer: 
:+1:

**Comment by chris2fr** [comment]
Hey, I liked the @kohei-takata, I liked the Label:Next release. Will we be able to soon have bulk importing and exporting? I think that it would be really nifty.

**Comment by seshonaar** [comment]
Any thoughts on the content separation idea @sferra dropped in? For me this would be a fantastic feature, as it comes a bit unnatural to have 'yet another editor'. I guess we all already have a favorite editor... (VSCode for me)
