### ISSUE TITLE
Click on search notes field leads to showing up empty result search component

### ISSUE THREAD

**Issue by LetItRock** [BoostIO/Boostnote#555]
Hello,
I have one suggestion - to show result component of searching notes only when user typed something in search field. For me it doesn't make sense to show this empty list component on search field click. Correct me please if I'm wrong and there is some other reason to do that.

![1](https://cloud.githubusercontent.com/assets/2607232/25765310/9fe25cec-31ec-11e7-8b6e-625f8def9e20.png)
![2](https://cloud.githubusercontent.com/assets/2607232/25765572/ff8dc9e6-31ed-11e7-90bd-ed992ccf8fc1.png)

**Comment by kazup01** [comment]
Hi @LetItRock san, thank you for your feedback!

Current search function has several problems as you say, so we want to improve it like below. 
What do you think about these?

- **Search bar as filter instead of dropdown** #152
- **Context search on snippet note** #306
- **Delete the previous search word** #400
- **Filter like GitHub issue** (like below image)
<img width="446" alt="6fd39c7bea1ca91fb1e989d7c92986de" src="https://cloud.githubusercontent.com/assets/8602615/25796240/b5a69e7a-3413-11e7-837a-f1d7875e8372.png">

**Comment by LetItRock** [comment]
Hi @kazup01 , 
it would be really great to see this functionality in search bar. 
I think that after this changes - user will have less interaction with search. I mean that after first search he will still have all searched/filtered result, so he won't need to type it again. I have this situation pretty often, when I want to search something and after check I recognize that this is not what I looked for, so I need to type it again and check another note.
Filtering is also good idea because it will give possibility to cut search result to something more specific.
I have some suggestions - we could add filtering by: type note, snippet; by tag; folder; starred; (date/range).

**Comment by kazup01** [comment]
Hi @LetItRock san, "Search bar as filter instead of dropdown" and "Delete the previous search word" are released at v0.8.10!

**Comment by kazup01** [comment]
`Context search on snippet note` and `Filter like GitHub issue` are need more time.
