### ISSUE TITLE
400 Bad Request

### ISSUE THREAD

**Issue by viczem** [BoostIO/Boostnote#685]
![](http://i.imgur.com/1heVYKm.png)

**Comment by kazup01** [comment]
Are you tried the latest version with `git pull`?

**Comment by viczem** [comment]
I just installed Boostnote from here: https://aur.archlinux.org/packages/boostnote

**Comment by asmsuechan** [comment]
I made it silent already. https://github.com/BoostIO/Boostnote/pull/664

**Comment by clone1612** [comment]
The problem is that for the Arch Linux package we build from source, compile for production and install it (roughly said). But since the source code does not contain the correct url with id building from source and compiling will lead to failed requests.

So to summarize the problem:
- Package for Arch Linux is build, compiled for production and then installed all from the source code (this repo)
- Url present in the source code does not contain the analytics id so requests to that url will fail

**Comment by kazup01** [comment]
Hi @viczem , how about this state?

**Comment by viczem** [comment]
It was fixed by @clone1612 on AUR side
