### ISSUE TITLE
Unable to build (Arch)

### ISSUE THREAD

**Issue by MichalEmbiq** [BoostIO/Boostnote#713]
`npm ERR! May not delete: /tmp/yaourt-tmp-mm/aur-boostnote/src/Boostnote-v.0.8.11/node_modules/.bin
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/mm/.npm/_logs/2017-07-18T07_15_15_233Z-debug.log
==> ERROR: A failure occurred in build().
    Aborting...
==> ERROR: Makepkg was unable to build boostnote.`

Logs: [https://pastebin.com/PDqE1G8P](url)

**Comment by emaren84** [comment]
Have you tried to build it under npm less than v5?

**Comment by clone1612** [comment]
Arch package maintainer here. Fixed it by moving to yarn instead of npm during installation so you should be able to install now. Issue seems to be related to a recent npm release since it did not happen when the latest version of Boostnote was released. I will look into it but by using yarn everyone should be able to install it without issues once again.

**Comment by MichalEmbiq** [comment]
Everything works now. @clone1612 thank you.

Logs from successful installation: https://pastebin.com/4XmpJTLd
