### ISSUE TITLE
Japanese is not caught in search feature

### ISSUE THREAD

**Issue by kazup01** [BoostIO/Boostnote#799]
refs: #766 
macOS Sierra 10.12.6
Boostnote v0.8.14

<img width="729" alt="screen shot 0029-08-13 at 7 33 57 pm" src="https://user-images.githubusercontent.com/8602615/29248890-867a3a2a-805e-11e7-9c86-94f6cc4c1aa6.png">

**Comment by asmsuechan** [comment]
The reason why this issue happens is that because the `context` is narrowed in each type.

To take 'こんにちは' for example, I typed 'k' at the first moment. Then Boostnote tries to search 'k' from **current notes (in the folder I focus)**. And the result is shown in NoteList and set them as current notes. So when next time I type 'o' that it means I typed 'こ', the search result of 'こ' from previous notes ( the result of 'k') is shown.

## Temporary solution
You should copy&paste in the input for now.

## Solution
To solve this issue, the search and NoteList have to connect each other. So I have to refactor them (because it's separated now).

**Comment by asmsuechan** [comment]
https://github.com/BoostIO/Boostnote/pull/954
