### ISSUE TITLE
Link not working

### ISSUE THREAD

**Issue by asmsuechan** [BoostIO/Boostnote#821]
# context
It doesn't open the correct page, it opens a blank page.

![out5](https://user-images.githubusercontent.com/11307908/29519976-51bafede-86ba-11e7-99b7-962462f8abd3.gif)
There's no error.
# expect
It opens the page as I actually write.

# environment
Ubuntu 16.04 LTS

**Comment by MPoppleton** [comment]
I don't have this issue

**Comment by asmsuechan** [comment]
Hi, @MPoppleton. Thank you so much for your information. Well, I guess it's because of my environment.

**Comment by yashha** [comment]
I also don't have the problem on Ubuntu 16.04.03 LTS

**Comment by KuangLei** [comment]
@asmsuechan I think this issue is due to Chrome.  

* First, before you clicked the link, Chrome had been already open, but when you clicked the link, the Chrome opened up a new window instead of opening the link in the previous window, which meant **Chrome goes into an error**.
* Second, **the `shell.openExternal(url)` itself and the code to call `shell.openExternal(url)`** shouldn't be affected by OS or Browser. it runs well on our computer, so it **is correct**.

Try to update your Chrome and try again.  

Thanks.

**Comment by mhpreiman** [comment]
I also have this problem on Boostnote desktop version (Windows 10).

**Comment by Rokt33r** [comment]
@mhpreiman The bug has been reported already.

**Comment by raffienficiaud** [comment]
I have this problem in Win8.1 and OSX10.13.
