### ISSUE TITLE
Note dissapered

### ISSUE THREAD

**Issue by vcvetkovs** [BoostIO/Boostnote#845]
Please paste some **screenshots** with the **developer tool** open if you report a bug.
I have had note which were disappeared after restart. How I can restore it?

**Comment by kazup01** [comment]
Could you paste screenshot with the developer tool? I can't know what the cause is.

**Comment by vcvetkovs** [comment]
![image](https://user-images.githubusercontent.com/6433851/30035038-7cb4f41a-91ae-11e7-8d7f-7656a1eaa58c.png)

**Comment by kazup01** [comment]
Did you create Markdown snippet (NOT markdown note)? If you created it, might be the cause of this issue. But this bug is fixed after v0.8.13. #780
<img width="545" alt="screen shot 0029-09-05 at 2 30 54 am" src="https://user-images.githubusercontent.com/8602615/30035199-738293e6-91e2-11e7-98a3-54c1a5cddac5.png">

**Comment by vcvetkovs** [comment]
Doesn't understand what is difference?
