### ISSUE TITLE
uninstall

### ISSUE THREAD

**Issue by ghosttie** [BoostIO/Boostnote#852]
How do I uninstall it on Windows?  It doesn't show up in "Apps & features" or "Programs and Features"

**Comment by kazup01** [comment]
I don't know your dev environment and this is not a Boostnote question.

**Comment by ghosttie** [comment]
I don't understand - there is no dev environment, I'm an end user.  I've installed Boostnote and now I can't uninstall it...

**Comment by KuangLei** [comment]
@ghosttie Make sure you have used `boost` instead of `boostnote` in your search of "App & features".  
![App & features](https://user-images.githubusercontent.com/12217600/30211839-0dd8ea22-94d5-11e7-879c-668b935250d8.png)  

If you still can't find it and you want to free the space, you can go to `C:\Users\YourUsername\AppData\Local` and delete the folder named `boost` in it to remove the Boostnote manually.  

Thanks.

**Comment by ghosttie** [comment]
Oh, that's it, thanks
