### ISSUE TITLE
[Request] Store note's content in markdown files

### ISSUE THREAD

**Issue by robachmann** [BoostIO/Boostnote#900]
Notes are currently stored in the `content`'s section of a `.cson` file. I would strongly suggest to store the content in a separate markdown file, so ...
- content can be edited in other markdown and text editors 
- the file can be opened and displayed in other markdown readers 
- exporting to markdown is already given/obsolete

the file name could be derived from the first line, e.g. "# Notes 2017-09-24" -> "notes-2017-09-24.md"

**Comment by asmsuechan** [comment]
Hi, @robachmann. I don't plan to change the data structure for now because there's a lot of things to consider such as data migration and tags and so on and so forth. So it's nearly impossible to implement it immediately.
FYI, there's a converter from .cson to .md made by a user: https://github.com/viko16/boost2fs
