### ISSUE TITLE
Add spell checking

### ISSUE THREAD

**Issue by beta-tank** [BoostIO/Boostnote#903]
Maybe you can add [electron-spellchecker](https://github.com/electron-userland/electron-spellchecker) to editor?

**Comment by mikeotoole** [comment]
👍

**Comment by UnicornForest** [comment]
> This feature is out of scope. 

Spell checking is out of scope for a note taking app?

**Comment by ewellinger** [comment]
Related to issue #76 and #1469.

**Comment by coreybeaumont** [comment]
agreed spell check has to be a fundamental feature of any note taking app. Right now after my note is complete I have to paste it into Atom or Sublime, toggle spell check, make edits, then paste it back into  BN.

**Comment by NamedKitten** [comment]
I just have a script that parses the cson notes and passes them through to aspell...
Even just highlighting misspelled words would be great.

**Comment by ehhc** [comment]
can you have a look at https://github.com/BoostIO/Boostnote/issues/2176 .. But it is not perfect..

**Comment by dissolved** [comment]
Yes, a note taking app needs spell checking for sure!

**Comment by ehhc** [comment]
Hey guys,
just a short update: the maintainer of boostnote and i do have a different view on the scope and the implementation of this feature. As i understood it, my PR will not be merged therefore.
Sorry to say that but i can't do something about that feature anymore (and due to the huge amount of work i invested into my PR i feel a bit demotivated to try it again using the way the maintainer would like to have it. You can see a part of the discussion here: #2176 )

Sorry to let you down but i will not continue to work on it
