### ISSUE TITLE
Can't Create New Note (stuck on screen to select note type)

### ISSUE THREAD

**Issue by xguse** [BoostIO/Boostnote#939]
![boostnote](https://user-images.githubusercontent.com/138931/31235934-b3a11c7c-a9c0-11e7-9bb5-13edc97ddd77.png)

Clicking on either of the options results in the uncaught error.

I am running uptodate Arch Linux and used the PKGBUILD from the AUR.

**Comment by PureCS** [comment]
I tried compiling v0.8.15 yesterday on windows 64 using grunt, and had this same issue. I had to use a pre-compiled binary to get it to work, you can get them from [here](https://github.com/BoostIO/boost-releases).

**Comment by clone1612** [comment]
Do you by any chance have the analytics enabled? Maintainer of the Arch package here and since we build from source analytics does not work. I have no problem creating notes while it’s disabled (latest build + up to date Arch + analytics disabled). Tried looking for different causes but did not find any.

For those wondering why, also the reason why @PureCS his build fails, is that the ID for connecting to their analytics server is not present in the source code (just a placeholder). It’s added during packaging the releases. Seems a failed connect that isn’t yet caught.

**Comment by PureCS** [comment]
Thank you for your response, it seems to be the issue.

**Comment by clone1612** [comment]
I have pushed an update for the Arch package @xguse which should already fix the issues you're experiencing. Let me know if any problems remain and I'll try to find a solution for them.

**Comment by NicoHood** [comment]
Please remove this analytics stuff completely.

@clone1612 Can you maybe open a PR with the changes you made to remove analytics? Maybe more distributions/people will use your patches then. I really appreciate your work :)

**Comment by xguse** [comment]
Dear god PLEASE do remove the analytics.

**Comment by xguse** [comment]
@clone1612 : thank you!  I am now able to create new notes!

And as an added bonus, my net activity doesn't spike every 5 or so seconds anymore.

Can't wait to actually test this app out!
