### ISSUE TITLE
Style Sheet Injection bug (maybe not vulnerability)

### ISSUE THREAD

**Issue by elliptic-shiho** [BoostIO/Boostnote#957]
I found a bug: Style Sheet Injection (not XSS, It is (maybe) not dangerous/not vulnerability)

Environment: 
OS: Any OS (I reprodeced ubuntu 16.04 and Windows 10)
Version: Boostnote 0.8.15

Reproduce:
1. Set `Editor Font Family` to `"Migu 1M";} body {background-color: red !important; font-family: "Migu 1M"`.
2. Save Settings and view any note

Result:  Background color of Note has changed, It was caused by injected stylesheet.

This bug caused by this: https://github.com/BoostIO/Boostnote/blob/95d74d1ca2206ed18add0348682af0063a5ac5b0/browser/components/MarkdownPreview.js#L37

Obviously, we can see same/similar bug at `Editor Font Size`, `Preview Font Family` and `Preview Font Size` (and other?).

**Comment by asmsuechan** [comment]
Hi, @elliptic-shiho. Thank you for opening an issue!

> not XSS, It is (maybe) not dangerous/not vulnerability

Yes, I don't think they're crucial security risks because Boostnote is managed only on localhost, and there's no probability to connect on the Internet from the application itself but AMA.

MY OPINION:
I want Boostnote to be hackable (e.g. https://github.com/BoostIO/Boostnote/issues/886#issuecomment-333234919) so I'd say it should leave the door open to customize by OSS and injectable.

However, I'm not a security man, so there are chances that I said nonsense. If you feel some of the security risks are crucial, please suggest what it is.

Thanks,

**Comment by elliptic-shiho** [comment]
Hi, @asmsuechan.

I think this is not vulnerable, also in the future, because Electron is based Chromium. (If Electron was based IE, we can XSS by `expression(alert(1))` effortlessly)

The "Hackable" concept is very good! I agree that opinion.

**Comment by asmsuechan** [comment]
> I think this is not vulnerable, also in the future, because Electron is based Chromium. (If Electron was based IE, we can XSS by expression(alert(1)) effortlessly)

I got it. Thank you for your advice!

> The "Hackable" concept is very good! I agree that opinion.

Thank you for your agreement :smile:
